# Generated by Django 4.2.2 on 2023-06-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_static_ons_data_delete_static'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Static_ONS_Data',
            new_name='StaticOnsData',
        ),
    ]
