# Generated by Django 4.2.2 on 2023-06-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_static_ons_data_staticonsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticOnsData',
        ),
    ]
