# Generated by Django 4.2.2 on 2023-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_staticonsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticonsdata',
            name='date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticonsdata',
            name='district',
            field=models.CharField(default='Tower Hamlets', max_length=300),
            preserve_default=False,
        ),
    ]
