# Generated by Django 4.2.2 on 2023-06-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_staticonsdata_date_staticonsdata_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='project',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.JSONField(default='default'),
            preserve_default=False,
        ),
    ]
