# Generated by Django 4.2.2 on 2023-06-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_location_project_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
