# Generated by Django 4.2.2 on 2023-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_location_project_alter_location_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default='No description', max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='No description', max_length=400),
        ),
    ]
