# Generated by Django 4.2.2 on 2023-06-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_location_description_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.JSONField(default=list),
        ),
    ]
