# Generated by Django 4.2.2 on 2023-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_location_project_remove_project_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(default='No notes yet'),
        ),
    ]
