import re
import pprint

computer_friendly_names = {
"Economic activity rate - aged 16-64": 'econ_activity_rate_16_64',
"Employment rate - aged 16-64": 'employment_rate_16_64',
"% aged 16-64 who are employees": 'p_are_employees_16_64',
"% aged 16-64 who are self employed": 'p_self_employed_16_64',
"Unemployment rate - aged 16-64": 'unemployment_rate_16_64',
"% who are economically inactive - aged 16-64": '16_64',
"% of economically inactive who want a job": '',
"Economic activity rate - aged 16-64": '16_64',
"Economic activity rate - aged 16-19": '16_19',
"Economic activity rate - aged 20-24": '20_24',
"Economic activity rate - aged 25-34": '',
"Economic activity rate - aged 35-49": '',
"Economic activity rate - aged 50+": '',
"Economic activity rate - aged 50-64": '',
"Economic activity rate - aged 65+": '',
"% of economically inactive student": '',
"% of economically inactive looking after family/home": '',
"% of economically inactive temporary sick": '',
"% of economically inactive long-term sick": '',
"% of economically inactive discouraged": '',
"% of economically inactive retired": '',
"% of economically inactive other": '',
"Unemployment rate - aged 16-19": '16_19',
"Unemployment rate - aged 20-24": '',
"Unemployment rate - aged 25-34": '',
"Unemployment rate - aged 35-49": '',
"Unemployment rate - aged 50+": '',
"Unemployment rate - aged 50-64": '',
"Unemployment rate - aged 65+": '',
"% of white - aged 16-64": '16_64',
"% of white - aged 16-19": '16_19',
"% of white - aged 20-24": '',
"% of white - aged 25-49": '',
"% of white - aged 50+": '',
"% of ethnic minority - aged 16-64": '16_64',
"% of ethnic minority - aged 16-19": '16_19',
"% of ethnic minority - aged 20-24": '',
"% of ethnic minority - aged 25-49": '',
"% of ethnic minority - aged 50+": '',
"% in employment working full-time - aged 16-64": '16_64',
"% in employment working full-time - aged 16-19": '16_19',
"% in employment working full-time - aged 20-24": '',
"% in employment working full-time - aged 25-49": '',
"% in employment working full-time - aged 50+": '',
"% in employment working part-time - aged 16-64": '16_64',
"% in employment working part-time - aged 16-19": '16_19',
"% in employment working part-time - aged 20-24": '',
"% in employment working part-time - aged 25-49": '',
"% in employment working part-time - aged 50+": '',
"% of all in employment who work under 10 hours": '',
"% of all in employment who work 10-34 hours": '',
"% of all in employment who work 35-44 hours": '',
"% of all in employment who work 45 hours or more": '',
"% all in employment who work in - A:agriculture and fishing (SIC 2007)": '',
"% all in employment who work in - B,D,E:energy and water (SIC 2007)": '',
"% all in employment who work in - C:manufacturing (SIC 2007)": '',
"% all in employment who work in - F:construction (SIC 2007)": '',
"% all in employment who work in - G,I:distribution, hotels and restaurants (SIC 2007)": '',
"% all in employment who work in - H,J:transport and communications (SIC 2007)": '',
"% all in employment who work in - K-N:banking, finance and insurance (SIC 2007)": '',
"% all in employment who work in - O-Q:public admin. education and health (SIC 2007)": '',
"% all in employment who work in - R-U:other services (SIC 2007)": '',
"% all in employment who work in - G-U:total services (SIC 2007)": '',
"all persons employed in public sector as % of all persons in employment": '',
"% with degree or equivalent and above - aged 16-64": '16_64',
"% with degree or equivalent and above - aged 16-19": '16_19',
"% with degree or equivalent and above - aged 20-24": '',
"% with degree or equivalent and above - aged 25-29": '',
"% with degree or equivalent and above - aged 30-39": '',
"% with degree or equivalent and above - aged 40-49": '',
"% with degree or equivalent and above - aged 50-64": '',
"% with higher education below degree level - aged 16-64": '16_64',
"% with higher education below degree level - aged 16-19": '16_19',
"% with higher education below degree level - aged 20-24": '',
"% with higher education below degree level - aged 25-29": '',
"% with higher education below degree level - aged 30-39": '',
"% with higher education below degree level - aged 40-49": '',
"% with higher education below degree level - aged 50-64": '',
"% with GCE A level or equivalent - aged 16-64": '16_64',
"% with GCE A level or equivalent - aged 16-19": '16_19',
"% with GCE A level or equivalent - aged 20-24": '',
"% with GCE A level or equivalent - aged 25-29": '',
"% with GCE A level or equivalent - aged 30-39": '',
"% with GCE A level or equivalent - aged 40-49": '',
"% with GCE A level or equivalent - aged 50-64": '',
"% with GCSE grades A-C or equivalent - aged 16-64": '16_64',
"% with GCSE grades A-C or equivalent - aged 16-19": '16_19',
"% with GCSE grades A-C or equivalent - aged 20-24": '',
"% with GCSE grades A-C or equivalent - aged 25-29": '',
"% with GCSE grades A-C or equivalent - aged 30-39": '',
"% with GCSE grades A-C or equivalent - aged 40-49": '',
"% with GCSE grades A-C or equivalent - aged 50-64": '',
"% with other qualifications (GCSE) - aged 16-64": '16_64',
"% with other qualifications (GCSE) - aged 16-19": '16_19',
"% with other qualifications (GCSE) - aged 20-24": '',
"% with other qualifications (GCSE) - aged 25-29": '',
"% with other qualifications (GCSE) - aged 30-39": '',
"% with other qualifications (GCSE) - aged 40-49": '',
"% with other qualifications (GCSE) - aged 50-64": '',
"% with no qualifications (GCSE) - aged 16-64": '16_64',
"% with no qualifications (GCSE) - aged 16-19": '16_19',
"% with no qualifications (GCSE) - aged 20-24": '',
"% with no qualifications (GCSE) - aged 25-29": '',
"% with no qualifications (GCSE) - aged 30-39": '',
"% with no qualifications (GCSE) - aged 40-49": '',
"% with no qualifications (GCSE) - aged 50-64": '',
"% with NVQ4+ - aged 16-64": '16_64',
"% with NVQ4+ - aged 16-19": '16_19',
"% with NVQ4+ - aged 20-24": '',
"% with NVQ4+ - aged 25-29": '',
"% with NVQ4+ - aged 30-39": '',
"% with NVQ4+ - aged 40-49": '',
"% with NVQ4+ - aged 50-64": '',
"% with NVQ3 only - aged 16-64": '16_64',
"% with NVQ3 only - aged 16-19": '16_19',
"% with NVQ3 only - aged 20-24": '',
"% with NVQ3 only - aged 25-29": '',
"% with NVQ3 only - aged 30-39": '',
"% with NVQ3 only - aged 40-49": '',
"% with NVQ3 only - aged 50-64": '',
"% with Trade Apprenticeships - aged 16-64": '16_64',
"% with Trade Apprenticeships - aged 16-19": '16_19',
"% with Trade Apprenticeships - aged 20-24": '',
"% with Trade Apprenticeships - aged 25-29": '',
"% with Trade Apprenticeships - aged 30-39": '',
"% with Trade Apprenticeships - aged 40-49": '',
"% with Trade Apprenticeships - aged 50-64": '',
"% with NVQ2 only - aged 16-64": '16_64',
"% with NVQ2 only - aged 16-19": '16_19',
"% with NVQ2 only - aged 20-24": '',
"% with NVQ2 only - aged 25-29": '',
"% with NVQ2 only - aged 30-39": '',
"% with NVQ2 only - aged 40-49": '',
"% with NVQ2 only - aged 50-64": '',
"% with NVQ1 only - aged 16-64": '16_64',
"% with NVQ1 only - aged 16-19": '16_19',
"% with NVQ1 only - aged 20-24": '',
"% with NVQ1 only - aged 25-29": '',
"% with NVQ1 only - aged 30-39": '',
"% with NVQ1 only - aged 40-49": '',
"% with NVQ1 only - aged 50-64": '',
"% with other qualifications (NVQ) - aged 16-64": '16_64',
"% with other qualifications (NVQ) - aged 16-19": '16_19',
"% with other qualifications (NVQ) - aged 20-24": '',
"% with other qualifications (NVQ) - aged 25-29": '',
"% with other qualifications (NVQ) - aged 30-39": '',
"% with other qualifications (NVQ) - aged 40-49": '',
"% with other qualifications (NVQ) - aged 50-64": '',
"% with no qualifications (NVQ) - aged 16-64": '16_64',
"% with no qualifications (NVQ) - aged 16-19": '16_19',
"% with no qualifications (NVQ) - aged 20-24": '',
"% with no qualifications (NVQ) - aged 25-29": '',
"% with no qualifications (NVQ) - aged 30-39": '',
"% with no qualifications (NVQ) - aged 40-49": '',
"% with no qualifications (NVQ) - aged 50-64": '',
"% with NVQ3+ - aged 16-64": '16_64',
"% with NVQ2+ - aged 16-64": '16_64',
"% with NVQ1+ - aged 16-64": '16_64',
"% of all people aged 16+ who are male": '',
"% of all people aged 16+ who are female": '',
"% of all 16+ who are aged 16-19": '16_19',
"% of all 16+ who are aged 20-24": '',
"% of all 16+ who are aged 25-34": '',
"% of all 16+ who are aged 35-49": '',
"% of all 16+ who are aged 50-64": '',
"% of all 16+ who are aged 65+": '',
}

new_computer_friendly_names = {}

for key, value in computer_friendly_names.items():
    match = re.search(r'(\d{2})-(\d{2})$', key)
    if match:
        reformatted_number = f'{match.group(1)}_{match.group(2)}'
        new_computer_friendly_names[key] = reformatted_number
    else:
        new_computer_friendly_names[key] = value


pprint_string = pprint.pformat(new_computer_friendly_names)
print(pprint_string)
print(len(computer_friendly_names))