import pprint

original_dict = {'A : Agriculture, forestry and fishing 0 to 4': '',
 'A : Agriculture, forestry and fishing 10 to 19': '',
 'A : Agriculture, forestry and fishing 100 to 249': '',
 'A : Agriculture, forestry and fishing 1000+': '',
 'A : Agriculture, forestry and fishing 20 to 49': '',
 'A : Agriculture, forestry and fishing 250 to 499': '',
 'A : Agriculture, forestry and fishing 5 to 9': '',
 'A : Agriculture, forestry and fishing 50 to 99': '',
 'A : Agriculture, forestry and fishing 500 to 999': '',
 'A : Agriculture, forestry and fishing Large (250+)': '',
 'A : Agriculture, forestry and fishing Medium-sized (50 to 249)': '',
 'A : Agriculture, forestry and fishing Micro (0 to 9)': '',
 'A : Agriculture, forestry and fishing Small (10 to 49)': '',
 'A : Agriculture, forestry and fishing Total': '',
 'B : Mining and quarrying 0 to 4': '',
 'B : Mining and quarrying 10 to 19': '',
 'B : Mining and quarrying 100 to 249': '',
 'B : Mining and quarrying 1000+': '',
 'B : Mining and quarrying 20 to 49': '',
 'B : Mining and quarrying 250 to 499': '',
 'B : Mining and quarrying 5 to 9': '',
 'B : Mining and quarrying 50 to 99': '',
 'B : Mining and quarrying 500 to 999': '',
 'B : Mining and quarrying Large (250+)': '',
 'B : Mining and quarrying Medium-sized (50 to 249)': '',
 'B : Mining and quarrying Micro (0 to 9)': '',
 'B : Mining and quarrying Small (10 to 49)': '',
 'B : Mining and quarrying Total': '',
 'C : Manufacturing 0 to 4': '',
 'C : Manufacturing 10 to 19': '',
 'C : Manufacturing 100 to 249': '',
 'C : Manufacturing 1000+': '',
 'C : Manufacturing 20 to 49': '',
 'C : Manufacturing 250 to 499': '',
 'C : Manufacturing 5 to 9': '',
 'C : Manufacturing 50 to 99': '',
 'C : Manufacturing 500 to 999': '',
 'C : Manufacturing Large (250+)': '',
 'C : Manufacturing Medium-sized (50 to 249)': '',
 'C : Manufacturing Micro (0 to 9)': '',
 'C : Manufacturing Small (10 to 49)': '',
 'C : Manufacturing Total': '',
 'D : Electricity, gas, steam and air conditioning supply 0 to 4': '',
 'D : Electricity, gas, steam and air conditioning supply 10 to 19': '',
 'D : Electricity, gas, steam and air conditioning supply 100 to 249': '',
 'D : Electricity, gas, steam and air conditioning supply 1000+': '',
 'D : Electricity, gas, steam and air conditioning supply 20 to 49': '',
 'D : Electricity, gas, steam and air conditioning supply 250 to 499': '',
 'D : Electricity, gas, steam and air conditioning supply 5 to 9': '',
 'D : Electricity, gas, steam and air conditioning supply 50 to 99': '',
 'D : Electricity, gas, steam and air conditioning supply 500 to 999': '',
 'D : Electricity, gas, steam and air conditioning supply Large (250+)': '',
 'D : Electricity, gas, steam and air conditioning supply Medium-sized (50 to 249)': '',
 'D : Electricity, gas, steam and air conditioning supply Micro (0 to 9)': '',
 'D : Electricity, gas, steam and air conditioning supply Small (10 to 49)': '',
 'D : Electricity, gas, steam and air conditioning supply Total': '',
 'E : Water supply; sewerage, waste management and remediation activities 0 to 4': '',
 'E : Water supply; sewerage, waste management and remediation activities 10 to 19': '',
 'E : Water supply; sewerage, waste management and remediation activities 100 to 249': '',
 'E : Water supply; sewerage, waste management and remediation activities 1000+': '',
 'E : Water supply; sewerage, waste management and remediation activities 20 to 49': '',
 'E : Water supply; sewerage, waste management and remediation activities 250 to 499': '',
 'E : Water supply; sewerage, waste management and remediation activities 5 to 9': '',
 'E : Water supply; sewerage, waste management and remediation activities 50 to 99': '',
 'E : Water supply; sewerage, waste management and remediation activities 500 to 999': '',
 'E : Water supply; sewerage, waste management and remediation activities Large (250+)': '',
 'E : Water supply; sewerage, waste management and remediation activities Medium-sized (50 to 249)': '',
 'E : Water supply; sewerage, waste management and remediation activities Micro (0 to 9)': '',
 'E : Water supply; sewerage, waste management and remediation activities Small (10 to 49)': '',
 'E : Water supply; sewerage, waste management and remediation activities Total': '',
 'F : Construction 0 to 4': '',
 'F : Construction 10 to 19': '',
 'F : Construction 100 to 249': '',
 'F : Construction 1000+': '',
 'F : Construction 20 to 49': '',
 'F : Construction 250 to 499': '',
 'F : Construction 5 to 9': '',
 'F : Construction 50 to 99': '',
 'F : Construction 500 to 999': '',
 'F : Construction Large (250+)': '',
 'F : Construction Medium-sized (50 to 249)': '',
 'F : Construction Micro (0 to 9)': '',
 'F : Construction Small (10 to 49)': '',
 'F : Construction Total': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 0 to 4': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 10 to 19': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 100 to 249': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 1000+': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 20 to 49': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 250 to 499': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 5 to 9': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 50 to 99': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 500 to 999': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Large (250+)': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Medium-sized (50 to 249)': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Micro (0 to 9)': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Small (10 to 49)': '',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Total': '',
 'H : Transportation and storage 0 to 4': '',
 'H : Transportation and storage 10 to 19': '',
 'H : Transportation and storage 100 to 249': '',
 'H : Transportation and storage 1000+': '',
 'H : Transportation and storage 20 to 49': '',
 'H : Transportation and storage 250 to 499': '',
 'H : Transportation and storage 5 to 9': '',
 'H : Transportation and storage 50 to 99': '',
 'H : Transportation and storage 500 to 999': '',
 'H : Transportation and storage Large (250+)': '',
 'H : Transportation and storage Medium-sized (50 to 249)': '',
 'H : Transportation and storage Micro (0 to 9)': '',
 'H : Transportation and storage Small (10 to 49)': '',
 'H : Transportation and storage Total': '',
 'I : Accommodation and food service activities 0 to 4': '',
 'I : Accommodation and food service activities 10 to 19': '',
 'I : Accommodation and food service activities 100 to 249': '',
 'I : Accommodation and food service activities 1000+': '',
 'I : Accommodation and food service activities 20 to 49': '',
 'I : Accommodation and food service activities 250 to 499': '',
 'I : Accommodation and food service activities 5 to 9': '',
 'I : Accommodation and food service activities 50 to 99': '',
 'I : Accommodation and food service activities 500 to 999': '',
 'I : Accommodation and food service activities Large (250+)': '',
 'I : Accommodation and food service activities Medium-sized (50 to 249)': '',
 'I : Accommodation and food service activities Micro (0 to 9)': '',
 'I : Accommodation and food service activities Small (10 to 49)': '',
 'I : Accommodation and food service activities Total': '',
 'J : Information and communication 0 to 4': '',
 'J : Information and communication 10 to 19': '',
 'J : Information and communication 100 to 249': '',
 'J : Information and communication 1000+': '',
 'J : Information and communication 20 to 49': '',
 'J : Information and communication 250 to 499': '',
 'J : Information and communication 5 to 9': '',
 'J : Information and communication 50 to 99': '',
 'J : Information and communication 500 to 999': '',
 'J : Information and communication Large (250+)': '',
 'J : Information and communication Medium-sized (50 to 249)': '',
 'J : Information and communication Micro (0 to 9)': '',
 'J : Information and communication Small (10 to 49)': '',
 'J : Information and communication Total': '',
 'K : Financial and insurance activities 0 to 4': '',
 'K : Financial and insurance activities 10 to 19': '',
 'K : Financial and insurance activities 100 to 249': '',
 'K : Financial and insurance activities 1000+': '',
 'K : Financial and insurance activities 20 to 49': '',
 'K : Financial and insurance activities 250 to 499': '',
 'K : Financial and insurance activities 5 to 9': '',
 'K : Financial and insurance activities 50 to 99': '',
 'K : Financial and insurance activities 500 to 999': '',
 'K : Financial and insurance activities Large (250+)': '',
 'K : Financial and insurance activities Medium-sized (50 to 249)': '',
 'K : Financial and insurance activities Micro (0 to 9)': '',
 'K : Financial and insurance activities Small (10 to 49)': '',
 'K : Financial and insurance activities Total': '',
 'L : Real estate activities 0 to 4': '',
 'L : Real estate activities 10 to 19': '',
 'L : Real estate activities 100 to 249': '',
 'L : Real estate activities 1000+': '',
 'L : Real estate activities 20 to 49': '',
 'L : Real estate activities 250 to 499': '',
 'L : Real estate activities 5 to 9': '',
 'L : Real estate activities 50 to 99': '',
 'L : Real estate activities 500 to 999': '',
 'L : Real estate activities Large (250+)': '',
 'L : Real estate activities Medium-sized (50 to 249)': '',
 'L : Real estate activities Micro (0 to 9)': '',
 'L : Real estate activities Small (10 to 49)': '',
 'L : Real estate activities Total': '',
 'M : Professional, scientific and technical activities 0 to 4': '',
 'M : Professional, scientific and technical activities 10 to 19': '',
 'M : Professional, scientific and technical activities 100 to 249': '',
 'M : Professional, scientific and technical activities 1000+': '',
 'M : Professional, scientific and technical activities 20 to 49': '',
 'M : Professional, scientific and technical activities 250 to 499': '',
 'M : Professional, scientific and technical activities 5 to 9': '',
 'M : Professional, scientific and technical activities 50 to 99': '',
 'M : Professional, scientific and technical activities 500 to 999': '',
 'M : Professional, scientific and technical activities Large (250+)': '',
 'M : Professional, scientific and technical activities Medium-sized (50 to 249)': '',
 'M : Professional, scientific and technical activities Micro (0 to 9)': '',
 'M : Professional, scientific and technical activities Small (10 to 49)': '',
 'M : Professional, scientific and technical activities Total': '',
 'N : Administrative and support service activities 0 to 4': '',
 'N : Administrative and support service activities 10 to 19': '',
 'N : Administrative and support service activities 100 to 249': '',
 'N : Administrative and support service activities 1000+': '',
 'N : Administrative and support service activities 20 to 49': '',
 'N : Administrative and support service activities 250 to 499': '',
 'N : Administrative and support service activities 5 to 9': '',
 'N : Administrative and support service activities 50 to 99': '',
 'N : Administrative and support service activities 500 to 999': '',
 'N : Administrative and support service activities Large (250+)': '',
 'N : Administrative and support service activities Medium-sized (50 to 249)': '',
 'N : Administrative and support service activities Micro (0 to 9)': '',
 'N : Administrative and support service activities Small (10 to 49)': '',
 'N : Administrative and support service activities Total': '',
 'O : Public administration and defence; compulsory social security 0 to 4': '',
 'O : Public administration and defence; compulsory social security 10 to 19': '',
 'O : Public administration and defence; compulsory social security 100 to 249': '',
 'O : Public administration and defence; compulsory social security 1000+': '',
 'O : Public administration and defence; compulsory social security 20 to 49': '',
 'O : Public administration and defence; compulsory social security 250 to 499': '',
 'O : Public administration and defence; compulsory social security 5 to 9': '',
 'O : Public administration and defence; compulsory social security 50 to 99': '',
 'O : Public administration and defence; compulsory social security 500 to 999': '',
 'O : Public administration and defence; compulsory social security Large (250+)': '',
 'O : Public administration and defence; compulsory social security Medium-sized (50 to 249)': '',
 'O : Public administration and defence; compulsory social security Micro (0 to 9)': '',
 'O : Public administration and defence; compulsory social security Small (10 to 49)': '',
 'O : Public administration and defence; compulsory social security Total': '',
 'P : Education 0 to 4': '',
 'P : Education 10 to 19': '',
 'P : Education 100 to 249': '',
 'P : Education 1000+': '',
 'P : Education 20 to 49': '',
 'P : Education 250 to 499': '',
 'P : Education 5 to 9': '',
 'P : Education 50 to 99': '',
 'P : Education 500 to 999': '',
 'P : Education Large (250+)': '',
 'P : Education Medium-sized (50 to 249)': '',
 'P : Education Micro (0 to 9)': '',
 'P : Education Small (10 to 49)': '',
 'P : Education Total': '',
 'Q : Human health and social work activities 0 to 4': '',
 'Q : Human health and social work activities 10 to 19': '',
 'Q : Human health and social work activities 100 to 249': '',
 'Q : Human health and social work activities 1000+': '',
 'Q : Human health and social work activities 20 to 49': '',
 'Q : Human health and social work activities 250 to 499': '',
 'Q : Human health and social work activities 5 to 9': '',
 'Q : Human health and social work activities 50 to 99': '',
 'Q : Human health and social work activities 500 to 999': '',
 'Q : Human health and social work activities Large (250+)': '',
 'Q : Human health and social work activities Medium-sized (50 to 249)': '',
 'Q : Human health and social work activities Micro (0 to 9)': '',
 'Q : Human health and social work activities Small (10 to 49)': '',
 'Q : Human health and social work activities Total': '',
 'R : Arts, entertainment and recreation 0 to 4': '',
 'R : Arts, entertainment and recreation 10 to 19': '',
 'R : Arts, entertainment and recreation 100 to 249': '',
 'R : Arts, entertainment and recreation 1000+': '',
 'R : Arts, entertainment and recreation 20 to 49': '',
 'R : Arts, entertainment and recreation 250 to 499': '',
 'R : Arts, entertainment and recreation 5 to 9': '',
 'R : Arts, entertainment and recreation 50 to 99': '',
 'R : Arts, entertainment and recreation 500 to 999': '',
 'R : Arts, entertainment and recreation Large (250+)': '',
 'R : Arts, entertainment and recreation Medium-sized (50 to 249)': '',
 'R : Arts, entertainment and recreation Micro (0 to 9)': '',
 'R : Arts, entertainment and recreation Small (10 to 49)': '',
 'R : Arts, entertainment and recreation Total': '',
 'S : Other service activities 0 to 4': '',
 'S : Other service activities 10 to 19': '',
 'S : Other service activities 100 to 249': '',
 'S : Other service activities 1000+': '',
 'S : Other service activities 20 to 49': '',
 'S : Other service activities 250 to 499': '',
 'S : Other service activities 5 to 9': '',
 'S : Other service activities 50 to 99': '',
 'S : Other service activities 500 to 999': '',
 'S : Other service activities Large (250+)': '',
 'S : Other service activities Medium-sized (50 to 249)': '',
 'S : Other service activities Micro (0 to 9)': '',
 'S : Other service activities Small (10 to 49)': '',
 'S : Other service activities Total': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 0 to 4': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 10 to 19': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 100 to 249': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 1000+': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 20 to 49': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 250 to 499': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 5 to 9': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 50 to 99': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 500 to 999': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Large (250+)': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Medium-sized (50 to 249)': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Micro (0 to 9)': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Small (10 to 49)': '',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Total': '',
 'U : Activities of extraterritorial organisations and bodies 0 to 4': '',
 'U : Activities of extraterritorial organisations and bodies 10 to 19': '',
 'U : Activities of extraterritorial organisations and bodies 100 to 249': '',
 'U : Activities of extraterritorial organisations and bodies 1000+': '',
 'U : Activities of extraterritorial organisations and bodies 20 to 49': '',
 'U : Activities of extraterritorial organisations and bodies 250 to 499': '',
 'U : Activities of extraterritorial organisations and bodies 5 to 9': '',
 'U : Activities of extraterritorial organisations and bodies 50 to 99': '',
 'U : Activities of extraterritorial organisations and bodies 500 to 999': '',
 'U : Activities of extraterritorial organisations and bodies Large (250+)': '',
 'U : Activities of extraterritorial organisations and bodies Medium-sized (50 to 249)': '',
 'U : Activities of extraterritorial organisations and bodies Micro (0 to 9)': '',
 'U : Activities of extraterritorial organisations and bodies Small (10 to 49)': '',
 'U : Activities of extraterritorial organisations and bodies Total': ''}

updated_dict = {}

for key, value in original_dict.items():
    new_value = key.replace(':','').replace(',', '').replace(')', '').replace('(', '').replace('+', 'plus').replace('-', '').replace(' ', '_').lower()
    new_value = '_'.join(word for word in new_value.split('_') if word)
    updated_dict[key] = new_value

pprint_string = pprint.pformat(updated_dict)
print(pprint_string)    