name_reformat = {
    '% aged 16-64 who are employees': 'are_employees_16_64',
    '% aged 16-64 who are self employed': 'self_employed_16_64',
    '% all in employment who work in - A:agriculture and fishing (SIC 2007)': 'sic_a',
    '% all in employment who work in - B,D,E:energy and water (SIC 2007)': 'sic_b_d_e',
    '% all in employment who work in - C:manufacturing (SIC 2007)': 'sic_c',
    '% all in employment who work in - F:construction (SIC 2007)': 'sic_f',
    '% all in employment who work in - G,I:distribution, hotels and restaurants (SIC 2007)': 'sic_g_i',
    '% all in employment who work in - G-U:total services (SIC 2007)': 'sic_total_services',
    '% all in employment who work in - H,J:transport and communications (SIC 2007)': 'sic_h_j',
    '% all in employment who work in - K-N:banking, finance and insurance (SIC 2007)': 'sic_k_n',
    '% all in employment who work in - O-Q:public admin. education and health (SIC 2007)': 'sic_o_q',
    '% all in employment who work in - R-U:other services (SIC 2007)': 'sic_r_u',
    '% in employment working full-time - aged 16-19': 'full_time_16_19',
    '% in employment working full-time - aged 16-64': 'full_time_16_64',
    '% in employment working full-time - aged 20-24': 'full_time_20_24',
    '% in employment working full-time - aged 25-49': 'full_time_25_49',
    '% in employment working full-time - aged 50+': 'full_time_over_50',
    '% in employment working part-time - aged 16-19': 'part_time_16_19',
    '% in employment working part-time - aged 16-64': 'part_time_16_64',
    '% in employment working part-time - aged 20-24': 'part_time_20_24',
    '% in employment working part-time - aged 25-49': 'part_time_25_49',
    '% in employment working part-time - aged 50+': 'part_time_over_50',
    '% of all 16+ who are aged 16-19': 'over_16_16_19',
    '% of all 16+ who are aged 20-24': 'over_16_20_24',
    '% of all 16+ who are aged 25-34': 'over_16_25_34',
    '% of all 16+ who are aged 35-49': 'over_16_35_49',
    '% of all 16+ who are aged 50-64': 'over_16_50_64',
    '% of all 16+ who are aged 65+': 'over_16_over_50',
    '% of all in employment who work 10-34 hours': 'work_10_34_hours',
    '% of all in employment who work 35-44 hours': 'work_35_44_hours',
    '% of all in employment who work 45 hours or more': 'work_over_45_hours',
    '% of all in employment who work under 10 hours': 'work_under_10_hours',
    '% of all people aged 16+ who are female': 'over_16_female',
    '% of all people aged 16+ who are male': 'over_16_male',
    '% of economically inactive discouraged': 'inact_discouraged',
    '% of economically inactive long-term sick': 'inact_sick_long',
    '% of economically inactive looking after family/home': 'inact_housewife',
    '% of economically inactive other': 'inact_other',
    '% of economically inactive retired': 'inact_retired',
    '% of economically inactive student': 'inact_student',
    '% of economically inactive temporary sick': 'inact_sick_temp',
    '% of economically inactive who want a job': 'inact_want_job',
    '% of ethnic minority - aged 16-19': 'ethnic_16_19',
    '% of ethnic minority - aged 16-64': 'ethnic_16_64',
    '% of ethnic minority - aged 20-24': 'ethnic_20_24',
    '% of ethnic minority - aged 25-49': 'ethnic_25_49',
    '% of ethnic minority - aged 50+': 'ethnic_over_50',
    '% of white - aged 16-19': 'white_16_19',
    '% of white - aged 16-64': 'white_16_64',
    '% of white - aged 20-24': 'white_20_24',
    '% of white - aged 25-49': 'white_25_49',
    '% of white - aged 50+': 'white_over_50',
    '% who are economically inactive - aged 16-64': 'inact_16_64',
    '% with GCE A level or equivalent - aged 16-19': 'alevel_16_19',
    '% with GCE A level or equivalent - aged 16-64': 'alevel_16_64',
    '% with GCE A level or equivalent - aged 20-24': 'alevel_20_24',
    '% with GCE A level or equivalent - aged 25-29': 'alevel_25_29',
    '% with GCE A level or equivalent - aged 30-39': 'alevel_30_39',
    '% with GCE A level or equivalent - aged 40-49': 'alevel_40_49',
    '% with GCE A level or equivalent - aged 50-64': 'alevel_50_64',
    '% with GCSE grades A-C or equivalent - aged 16-19': 'gcse_16_19',
    '% with GCSE grades A-C or equivalent - aged 16-64': 'gcse_16_64',
    '% with GCSE grades A-C or equivalent - aged 20-24': 'gcse_20_24',
    '% with GCSE grades A-C or equivalent - aged 25-29': 'gcse_25_29',
    '% with GCSE grades A-C or equivalent - aged 30-39': 'gcse_30_39',
    '% with GCSE grades A-C or equivalent - aged 40-49': 'gcse_40_49',
    '% with GCSE grades A-C or equivalent - aged 50-64': 'gcse_50_64',
    '% with NVQ1 only - aged 16-19': 'nvq1_16_19',
    '% with NVQ1 only - aged 16-64': 'nvq1_16_64',
    '% with NVQ1 only - aged 20-24': 'nvq1_20_24',
    '% with NVQ1 only - aged 25-29': 'nvq1_25_29',
    '% with NVQ1 only - aged 30-39': 'nvq1_30_39',
    '% with NVQ1 only - aged 40-49': 'nvq1_40_49',
    '% with NVQ1 only - aged 50-64': 'nvq1_50_64',
    '% with NVQ1+ - aged 16-64': 'at_least_nvq1_16_64',
    '% with NVQ2 only - aged 16-19': 'nvq2_16_19',
    '% with NVQ2 only - aged 16-64': 'nvq2_16_64',
    '% with NVQ2 only - aged 20-24': 'nvq2_20_24',
    '% with NVQ2 only - aged 25-29': 'nvq2_25_29',
    '% with NVQ2 only - aged 30-39': 'nvq2_30_39',
    '% with NVQ2 only - aged 40-49': 'nvq2_40_49',
    '% with NVQ2 only - aged 50-64': 'nvq2_50_64',
    '% with NVQ2+ - aged 16-64': 'at_least_nvq2_16_64',
    '% with NVQ3 only - aged 16-19': 'nvq3_16_19',
    '% with NVQ3 only - aged 16-64': 'nvq3_16_64',
    '% with NVQ3 only - aged 20-24': 'nvq3_20_24',
    '% with NVQ3 only - aged 25-29': 'nvq3_25_29',
    '% with NVQ3 only - aged 30-39': 'nvq3_30_39',
    '% with NVQ3 only - aged 40-49': 'nvq3_40_49',
    '% with NVQ3 only - aged 50-64': 'nvq3_50_64',
    '% with NVQ3+ - aged 16-64': 'at_least_nvq_3_16_64',
    '% with NVQ4+ - aged 16-19': 'at_least_nvq_4_16_19',
    '% with NVQ4+ - aged 16-64': 'at_least_nvq_4_16_64',
    '% with NVQ4+ - aged 20-24': 'at_least_nvq_4_20_24',
    '% with NVQ4+ - aged 25-29': 'at_least_nvq_4_25_29',
    '% with NVQ4+ - aged 30-39': 'at_least_nvq_4_30_39',
    '% with NVQ4+ - aged 40-49': 'at_least_nvq_4_40_49',
    '% with NVQ4+ - aged 50-64': 'at_least_nvq_4_50_64',
    '% with Trade Apprenticeships - aged 16-19': 'apprentice_16_19',
    '% with Trade Apprenticeships - aged 16-64': 'apprentice_16_64',
    '% with Trade Apprenticeships - aged 20-24': 'apprentice_20_24',
    '% with Trade Apprenticeships - aged 25-29': 'apprentice_25_29',
    '% with Trade Apprenticeships - aged 30-39': 'apprentice_30_39',
    '% with Trade Apprenticeships - aged 40-49': 'apprentice_40_49',
    '% with Trade Apprenticeships - aged 50-64': 'apprentice_50_64',
    '% with degree or equivalent and above - aged 16-19': 'degree_or_above_16_19',
    '% with degree or equivalent and above - aged 16-64': 'degree_or_above_16_64',
    '% with degree or equivalent and above - aged 20-24': 'degree_or_above_20_24',
    '% with degree or equivalent and above - aged 25-29': 'degree_or_above_25_29',
    '% with degree or equivalent and above - aged 30-39': 'degree_or_above_30_39',
    '% with degree or equivalent and above - aged 40-49': 'degree_or_above_40_49',
    '% with degree or equivalent and above - aged 50-64': 'degree_or_above_50_64',
    '% with higher education below degree level - aged 16-19': 'he_below_degree_16_19',
    '% with higher education below degree level - aged 16-64': 'he_below_degree_16_64',
    '% with higher education below degree level - aged 20-24': 'he_below_degree_20_24',
    '% with higher education below degree level - aged 25-29': 'he_below_degree_25_29',
    '% with higher education below degree level - aged 30-39': 'he_below_degree_30_39',
    '% with higher education below degree level - aged 40-49': 'he_below_degree_40_49',
    '% with higher education below degree level - aged 50-64': 'he_below_degree_50_64',
    '% with no qualifications (GCSE) - aged 16-19': 'no_qual_gcse_16_19',
    '% with no qualifications (GCSE) - aged 16-64': 'no_qual_gcse_16_64',
    '% with no qualifications (GCSE) - aged 20-24': 'no_qual_gcse_20_24',
    '% with no qualifications (GCSE) - aged 25-29': 'no_qual_gcse_25_29',
    '% with no qualifications (GCSE) - aged 30-39': 'no_qual_gcse_30_39',
    '% with no qualifications (GCSE) - aged 40-49': 'no_qual_gcse_40_49',
    '% with no qualifications (GCSE) - aged 50-64': 'no_qual_gcse_50_64',
    '% with no qualifications (NVQ) - aged 16-19': 'no_qual_nvq_16_19',
    '% with no qualifications (NVQ) - aged 16-64': 'no_qual_nvq_16_64',
    '% with no qualifications (NVQ) - aged 20-24': 'no_qual_nvq_20_24',
    '% with no qualifications (NVQ) - aged 25-29': 'no_qual_nvq_25_29',
    '% with no qualifications (NVQ) - aged 30-39': 'no_qual_nvq_30_39',
    '% with no qualifications (NVQ) - aged 40-49': 'no_qual_nvq_40_49',
    '% with no qualifications (NVQ) - aged 50-64': 'no_qual_nvq_50_64',
    '% with other qualifications (GCSE) - aged 16-19': 'other_qual_gcse_16_19',
    '% with other qualifications (GCSE) - aged 16-64': 'other_qual_gcse_16_64',
    '% with other qualifications (GCSE) - aged 20-24': 'other_qual_gcse_20_24',
    '% with other qualifications (GCSE) - aged 25-29': 'other_qual_gcse_25_29',
    '% with other qualifications (GCSE) - aged 30-39': 'other_qual_gcse_30_39',
    '% with other qualifications (GCSE) - aged 40-49': 'other_qual_gcse_40_49',
    '% with other qualifications (GCSE) - aged 50-64': 'other_qual_gcse_50_64',
    '% with other qualifications (NVQ) - aged 16-19': 'other_qual_nvq_16_19',
    '% with other qualifications (NVQ) - aged 16-64': 'other_qual_nvq_16_64',
    '% with other qualifications (NVQ) - aged 20-24': 'other_qual_nvq_20_24',
    '% with other qualifications (NVQ) - aged 25-29': 'other_qual_nvq_25_29',
    '% with other qualifications (NVQ) - aged 30-39': 'other_qual_nvq_30_39',
    '% with other qualifications (NVQ) - aged 40-49': 'other_qual_nvq_40_49',
    '% with other qualifications (NVQ) - aged 50-64': 'other_qual_nvq_50_64',
    'Economic activity rate - aged 16-19': 'econ_activity_16_19',
    'Economic activity rate - aged 16-64': 'econ_activity_16_64',
    'Economic activity rate - aged 20-24': 'econ_activity_20_24',
    'Economic activity rate - aged 25-34': 'econ_activity_25_34',
    'Economic activity rate - aged 35-49': 'econ_activity_35_49',
    'Economic activity rate - aged 50+': 'econ_activity_over_50',
    'Economic activity rate - aged 50-64': 'econ_activity_50_64',
    'Economic activity rate - aged 65+': 'econ_activity_over_65',
    'Employment rate - aged 16-64': 'employment_rate_16_64',
    'Unemployment rate - aged 16-19': 'unemployment_rate_16_19',
    'Unemployment rate - aged 16-64 ': 'unemployment_rate_16_64',
    'Unemployment rate - aged 20-24': 'unemployment_rate_20_24',
    'Unemployment rate - aged 25-34': 'unemployment_rate_25_34',
    'Unemployment rate - aged 35-49': 'unemployment_rate_35_49',
    'Unemployment rate - aged 50+': 'unemployment_rate_over_50',
    'Unemployment rate - aged 50-64': 'unemployment_rate_50_64',
    'Unemployment rate - aged 65+': 'unemployment_rate_over_65',
    'all persons employed in public sector as % of all persons in employment': 'employed_public_sector'
 }

column_reformat = {
    'DATE_NAME': 'date',
    'GEOGRAPHY_NAME': 'district',
    'GEOGRAPHY_CODE': 'code',
    'VARIABLE_NAME': 'indicator',
    'MEASURE_NAME': 'indicator',
    'ITEM_NAME': 'indicator',
    'C_AGE_NAME': 'indicator',
    'OBS_VALUE': 'value'
}

date_reformat = {
    'Jan 2013-Dec 2013': 2013,
    'Jan 2014-Dec 2014': 2014,
    'Jan 2015-Dec 2015': 2015,
    'Jan 2016-Dec 2016': 2016,
    'Jan 2017-Dec 2017': 2017,
    'Jan 2018-Dec 2018': 2018,
    'Jan 2019-Dec 2019': 2019,
    'Jan 2020-Dec 2020': 2020,
    'Jan 2021-Dec 2021': 2021,
    'Jan 2022-Dec 2022': 2022,
}

fert_reformat = {
    'Age specific fertility rate : Aged 20-24': 'fert_20_24',
    'Age specific fertility rate : Aged 25-29': 'fert_25_29',
    'Age specific fertility rate : Aged 30-34': 'fert_30_34',
    'Age specific fertility rate : Aged 35-39': 'fert_35_39',
    'Age specific fertility rate : Aged 40-44': 'fert_40_44',
    'Age specific fertility rate : Aged 45 and over': 'fert_over_45',
    'Age specific fertility rate : Aged under 18': 'fert_under_18',
    'Age specific fertility rate : Aged under 20': 'fert_under_20',
    'General fertility rate (GFR)': 'gfr',
    'Live births': 'live_births',
    'Total fertility rate (TFR)': 'tfr'
 }

h_e_reformat = {
    'Annual pay - gross 10 percentile': 'annual_pay_gross_10_percentile',
    'Annual pay - gross 20 percentile': 'annual_pay_gross_20_percentile',
    'Annual pay - gross 25 percentile': 'annual_pay_gross_25_percentile',
    'Annual pay - gross 30 percentile': 'annual_pay_gross_30_percentile',
    'Annual pay - gross 40 percentile': 'annual_pay_gross_40_percentile',
    'Annual pay - gross 60 percentile': 'annual_pay_gross_60_percentile',
    'Annual pay - gross 70 percentile': 'annual_pay_gross_70_percentile',
    'Annual pay - gross 75 percentile': 'annual_pay_gross_75_percentile',
    'Annual pay - gross 80 percentile': 'annual_pay_gross_80_percentile',
    'Annual pay - gross 90 percentile': 'annual_pay_gross_90_percentile',
    'Annual pay - gross Annual percentage change - median': 'annual_pay_gross_annual_percentage_change_median',
    'Annual pay - gross Median': 'annual_pay_gross_median',
    'Annual pay - gross Number of jobs': 'annual_pay_gross_number_of_jobs',
    'Annual pay - incentive 10 percentile': 'annual_pay_incentive_10_percentile',
    'Annual pay - incentive 20 percentile': 'annual_pay_incentive_20_percentile',
    'Annual pay - incentive 25 percentile': 'annual_pay_incentive_25_percentile',
    'Annual pay - incentive 30 percentile': 'annual_pay_incentive_30_percentile',
    'Annual pay - incentive 40 percentile': 'annual_pay_incentive_40_percentile',
    'Annual pay - incentive 60 percentile': 'annual_pay_incentive_60_percentile',
    'Annual pay - incentive 70 percentile': 'annual_pay_incentive_70_percentile',
    'Annual pay - incentive 75 percentile': 'annual_pay_incentive_75_percentile',
    'Annual pay - incentive 80 percentile': 'annual_pay_incentive_80_percentile',
    'Annual pay - incentive 90 percentile': 'annual_pay_incentive_90_percentile',
    'Annual pay - incentive Annual percentage change - median': 'annual_pay_incentive_annual_percentage_change_median',
    'Annual pay - incentive Median': 'annual_pay_incentive_median',
    'Annual pay - incentive Number of jobs': 'annual_pay_incentive_number_of_jobs',
    'Hourly pay - gross 10 percentile': 'hourly_pay_gross_10_percentile',
    'Hourly pay - gross 20 percentile': 'hourly_pay_gross_20_percentile',
    'Hourly pay - gross 25 percentile': 'hourly_pay_gross_25_percentile',
    'Hourly pay - gross 30 percentile': 'hourly_pay_gross_30_percentile',
    'Hourly pay - gross 40 percentile': 'hourly_pay_gross_40_percentile',
    'Hourly pay - gross 60 percentile': 'hourly_pay_gross_60_percentile',
    'Hourly pay - gross 70 percentile': 'hourly_pay_gross_70_percentile',
    'Hourly pay - gross 75 percentile': 'hourly_pay_gross_75_percentile',
    'Hourly pay - gross 80 percentile': 'hourly_pay_gross_80_percentile',
    'Hourly pay - gross 90 percentile': 'hourly_pay_gross_90_percentile',
    'Hourly pay - gross Annual percentage change - median': 'hourly_pay_gross_annual_percentage_change_median',
    'Hourly pay - gross Median': 'hourly_pay_gross_median',
    'Hourly pay - gross Number of jobs': 'hourly_pay_gross_number_of_jobs',
    'Hours worked - total 10 percentile': 'hours_worked_total_10_percentile',
    'Hours worked - total 20 percentile': 'hours_worked_total_20_percentile',
    'Hours worked - total 25 percentile': 'hours_worked_total_25_percentile',
    'Hours worked - total 30 percentile': 'hours_worked_total_30_percentile',
    'Hours worked - total 40 percentile': 'hours_worked_total_40_percentile',
    'Hours worked - total 60 percentile': 'hours_worked_total_60_percentile',
    'Hours worked - total 70 percentile': 'hours_worked_total_70_percentile',
    'Hours worked - total 75 percentile': 'hours_worked_total_75_percentile',
    'Hours worked - total 80 percentile': 'hours_worked_total_80_percentile',
    'Hours worked - total 90 percentile': 'hours_worked_total_90_percentile',
    'Hours worked - total Annual percentage change - median': 'hours_worked_total_annual_percentage_change_median',
    'Hours worked - total Median': 'hours_worked_total_median',
    'Hours worked - total Number of jobs': 'hours_worked_total_number_of_jobs',
    'Weekly pay - gross 10 percentile': 'weekly_pay_gross_10_percentile',
    'Weekly pay - gross 20 percentile': 'weekly_pay_gross_20_percentile',
    'Weekly pay - gross 25 percentile': 'weekly_pay_gross_25_percentile',
    'Weekly pay - gross 30 percentile': 'weekly_pay_gross_30_percentile',
    'Weekly pay - gross 40 percentile': 'weekly_pay_gross_40_percentile',
    'Weekly pay - gross 60 percentile': 'weekly_pay_gross_60_percentile',
    'Weekly pay - gross 70 percentile': 'weekly_pay_gross_70_percentile',
    'Weekly pay - gross 75 percentile': 'weekly_pay_gross_75_percentile',
    'Weekly pay - gross 80 percentile': 'weekly_pay_gross_80_percentile',
    'Weekly pay - gross 90 percentile': 'weekly_pay_gross_90_percentile',
    'Weekly pay - gross Annual percentage change - median': 'weekly_pay_gross_annual_percentage_change_median',
    'Weekly pay - gross Median': 'weekly_pay_gross_median',
    'Weekly pay - gross Number of jobs': 'weekly_pay_gross_number_of_jobs'
 }

business_counts_reformat = {'A : Agriculture, forestry and fishing 0 to 4': 'a_agriculture_forestry_and_fishing_0_to_4',
 'A : Agriculture, forestry and fishing 10 to 19': 'a_agriculture_forestry_and_fishing_10_to_19',
 'A : Agriculture, forestry and fishing 100 to 249': 'a_agriculture_forestry_and_fishing_100_to_249',
 'A : Agriculture, forestry and fishing 1000+': 'a_agriculture_forestry_and_fishing_1000plus',
 'A : Agriculture, forestry and fishing 20 to 49': 'a_agriculture_forestry_and_fishing_20_to_49',
 'A : Agriculture, forestry and fishing 250 to 499': 'a_agriculture_forestry_and_fishing_250_to_499',
 'A : Agriculture, forestry and fishing 5 to 9': 'a_agriculture_forestry_and_fishing_5_to_9',
 'A : Agriculture, forestry and fishing 50 to 99': 'a_agriculture_forestry_and_fishing_50_to_99',
 'A : Agriculture, forestry and fishing 500 to 999': 'a_agriculture_forestry_and_fishing_500_to_999',
 'A : Agriculture, forestry and fishing Large (250+)': 'a_agriculture_forestry_and_fishing_large_250plus',
 'A : Agriculture, forestry and fishing Medium-sized (50 to 249)': 'a_agriculture_forestry_and_fishing_mediumsized_50_to_249',
 'A : Agriculture, forestry and fishing Micro (0 to 9)': 'a_agriculture_forestry_and_fishing_micro_0_to_9',
 'A : Agriculture, forestry and fishing Small (10 to 49)': 'a_agriculture_forestry_and_fishing_small_10_to_49',
 'A : Agriculture, forestry and fishing Total': 'a_agriculture_forestry_and_fishing_total',
 'B : Mining and quarrying 0 to 4': 'b_mining_and_quarrying_0_to_4',
 'B : Mining and quarrying 10 to 19': 'b_mining_and_quarrying_10_to_19',
 'B : Mining and quarrying 100 to 249': 'b_mining_and_quarrying_100_to_249',
 'B : Mining and quarrying 1000+': 'b_mining_and_quarrying_1000plus',
 'B : Mining and quarrying 20 to 49': 'b_mining_and_quarrying_20_to_49',
 'B : Mining and quarrying 250 to 499': 'b_mining_and_quarrying_250_to_499',
 'B : Mining and quarrying 5 to 9': 'b_mining_and_quarrying_5_to_9',
 'B : Mining and quarrying 50 to 99': 'b_mining_and_quarrying_50_to_99',
 'B : Mining and quarrying 500 to 999': 'b_mining_and_quarrying_500_to_999',
 'B : Mining and quarrying Large (250+)': 'b_mining_and_quarrying_large_250plus',
 'B : Mining and quarrying Medium-sized (50 to 249)': 'b_mining_and_quarrying_mediumsized_50_to_249',
 'B : Mining and quarrying Micro (0 to 9)': 'b_mining_and_quarrying_micro_0_to_9',
 'B : Mining and quarrying Small (10 to 49)': 'b_mining_and_quarrying_small_10_to_49',
 'B : Mining and quarrying Total': 'b_mining_and_quarrying_total',
 'C : Manufacturing 0 to 4': 'c_manufacturing_0_to_4',
 'C : Manufacturing 10 to 19': 'c_manufacturing_10_to_19',
 'C : Manufacturing 100 to 249': 'c_manufacturing_100_to_249',
 'C : Manufacturing 1000+': 'c_manufacturing_1000plus',
 'C : Manufacturing 20 to 49': 'c_manufacturing_20_to_49',
 'C : Manufacturing 250 to 499': 'c_manufacturing_250_to_499',
 'C : Manufacturing 5 to 9': 'c_manufacturing_5_to_9',
 'C : Manufacturing 50 to 99': 'c_manufacturing_50_to_99',
 'C : Manufacturing 500 to 999': 'c_manufacturing_500_to_999',
 'C : Manufacturing Large (250+)': 'c_manufacturing_large_250plus',
 'C : Manufacturing Medium-sized (50 to 249)': 'c_manufacturing_mediumsized_50_to_249',
 'C : Manufacturing Micro (0 to 9)': 'c_manufacturing_micro_0_to_9',
 'C : Manufacturing Small (10 to 49)': 'c_manufacturing_small_10_to_49',
 'C : Manufacturing Total': 'c_manufacturing_total',
 'D : Electricity, gas, steam and air conditioning supply 0 to 4': 'd_electr_gas_air_conditioning_supply_0_to_4',
 'D : Electricity, gas, steam and air conditioning supply 10 to 19': 'd_electr_gas_air_conditioning_supply_10_to_19',
 'D : Electricity, gas, steam and air conditioning supply 100 to 249': 'd_electr_gas_air_conditioning_supply_100_to_249',
 'D : Electricity, gas, steam and air conditioning supply 1000+': 'd_electr_gas_air_conditioning_supply_1000plus',
 'D : Electricity, gas, steam and air conditioning supply 20 to 49': 'd_electr_gas_air_conditioning_supply_20_to_49',
 'D : Electricity, gas, steam and air conditioning supply 250 to 499': 'd_electr_gas_air_conditioning_supply_250_to_499',
 'D : Electricity, gas, steam and air conditioning supply 5 to 9': 'd_electr_gas_air_conditioning_supply_5_to_9',
 'D : Electricity, gas, steam and air conditioning supply 50 to 99': 'd_electr_gas_air_conditioning_supply_50_to_99',
 'D : Electricity, gas, steam and air conditioning supply 500 to 999': 'd_electr_gas_air_conditioning_supply_500_to_999',
 'D : Electricity, gas, steam and air conditioning supply Large (250+)': 'd_electr_gas_air_conditioning_supply_large_250plus',
 'D : Electricity, gas, steam and air conditioning supply Medium-sized (50 to 249)': 'd_electr_gas_air_conditioning_supply_mediumsized_50_to_249',
 'D : Electricity, gas, steam and air conditioning supply Micro (0 to 9)': 'd_electr_gas_air_conditioning_supply_micro_0_to_9',
 'D : Electricity, gas, steam and air conditioning supply Small (10 to 49)': 'd_electr_gas_air_conditioning_supply_small_10_to_49',
 'D : Electricity, gas, steam and air conditioning supply Total': 'd_electr_gas_air_conditioning_supply_total',
 'E : Water supply; sewerage, waste management and remediation activities 0 to 4': 'e_water_sup_sewage_waste_mgmt_0_to_4',
 'E : Water supply; sewerage, waste management and remediation activities 10 to 19': 'e_water_sup_sewage_waste_mgmt_10_to_19',
 'E : Water supply; sewerage, waste management and remediation activities 100 to 249': 'e_water_sup_sewage_waste_mgmt_100_to_249',
 'E : Water supply; sewerage, waste management and remediation activities 1000+': 'e_water_sup_sewage_waste_mgmt_1000plus',
 'E : Water supply; sewerage, waste management and remediation activities 20 to 49': 'e_water_sup_sewage_waste_mgmt_20_to_49',
 'E : Water supply; sewerage, waste management and remediation activities 250 to 499': 'e_water_sup_sewage_waste_mgmt_250_to_499',
 'E : Water supply; sewerage, waste management and remediation activities 5 to 9': 'e_water_sup_sewage_waste_mgmt_5_to_9',
 'E : Water supply; sewerage, waste management and remediation activities 50 to 99': 'e_water_sup_sewage_waste_mgmt_50_to_99',
 'E : Water supply; sewerage, waste management and remediation activities 500 to 999': 'e_water_sup_sewage_waste_mgmt_500_to_999',
 'E : Water supply; sewerage, waste management and remediation activities Large (250+)': 'e_water_sup_sewage_waste_mgmt_large_250plus',
 'E : Water supply; sewerage, waste management and remediation activities Medium-sized (50 to 249)': 'e_water_sup_sewage_waste_mgmt_mediumsized_50_to_249',
 'E : Water supply; sewerage, waste management and remediation activities Micro (0 to 9)': 'e_water_sup_sewage_waste_mgmt_micro_0_to_9',
 'E : Water supply; sewerage, waste management and remediation activities Small (10 to 49)': 'e_water_sup_sewage_waste_mgmt_small_10_to_49',
 'E : Water supply; sewerage, waste management and remediation activities Total': 'e_water_sup_sewage_waste_mgmt_total',
 'F : Construction 0 to 4': 'f_construction_0_to_4',
 'F : Construction 10 to 19': 'f_construction_10_to_19',
 'F : Construction 100 to 249': 'f_construction_100_to_249',
 'F : Construction 1000+': 'f_construction_1000plus',
 'F : Construction 20 to 49': 'f_construction_20_to_49',
 'F : Construction 250 to 499': 'f_construction_250_to_499',
 'F : Construction 5 to 9': 'f_construction_5_to_9',
 'F : Construction 50 to 99': 'f_construction_50_to_99',
 'F : Construction 500 to 999': 'f_construction_500_to_999',
 'F : Construction Large (250+)': 'f_construction_large_250plus',
 'F : Construction Medium-sized (50 to 249)': 'f_construction_mediumsized_50_to_249',
 'F : Construction Micro (0 to 9)': 'f_construction_micro_0_to_9',
 'F : Construction Small (10 to 49)': 'f_construction_small_10_to_49',
 'F : Construction Total': 'f_construction_total',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 0 to 4': 'g_whsale_retail_trd_repair_motor_vehic_0_to_4',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 10 to 19': 'g_whsale_retail_trd_repair_motor_vehic_10_to_19',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 100 to 249': 'g_whsale_retail_trd_repair_motor_vehic_100_to_249',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 1000+': 'g_whsale_retail_trd_repair_motor_vehic_1000plus',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 20 to 49': 'g_whsale_retail_trd_repair_motor_vehic_20_to_49',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 250 to 499': 'g_whsale_retail_trd_repair_motor_vehic_250_to_499',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 5 to 9': 'g_whsale_retail_trd_repair_motor_vehic_5_to_9',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 50 to 99': 'g_whsale_retail_trd_repair_motor_vehic_50_to_99',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles 500 to 999': 'g_whsale_retail_trd_repair_motor_vehic_500_to_999',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Large (250+)': 'g_whsale_retail_trd_repair_motor_vehic_large_250plus',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Medium-sized (50 to 249)': 'g_whsale_retail_trd_repair_motor_vehic_mediumsized_50_to_249',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Micro (0 to 9)': 'g_whsale_retail_trd_repair_motor_vehic_micro_0_to_9',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Small (10 to 49)': 'g_whsale_retail_trd_repair_motor_vehic_small_10_to_49',
 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles Total': 'g_whsale_retail_trd_repair_motor_vehic_total',
 'H : Transportation and storage 0 to 4': 'h_transportation_and_storage_0_to_4',
 'H : Transportation and storage 10 to 19': 'h_transportation_and_storage_10_to_19',
 'H : Transportation and storage 100 to 249': 'h_transportation_and_storage_100_to_249',
 'H : Transportation and storage 1000+': 'h_transportation_and_storage_1000plus',
 'H : Transportation and storage 20 to 49': 'h_transportation_and_storage_20_to_49',
 'H : Transportation and storage 250 to 499': 'h_transportation_and_storage_250_to_499',
 'H : Transportation and storage 5 to 9': 'h_transportation_and_storage_5_to_9',
 'H : Transportation and storage 50 to 99': 'h_transportation_and_storage_50_to_99',
 'H : Transportation and storage 500 to 999': 'h_transportation_and_storage_500_to_999',
 'H : Transportation and storage Large (250+)': 'h_transportation_and_storage_large_250plus',
 'H : Transportation and storage Medium-sized (50 to 249)': 'h_transportation_and_storage_mediumsized_50_to_249',
 'H : Transportation and storage Micro (0 to 9)': 'h_transportation_and_storage_micro_0_to_9',
 'H : Transportation and storage Small (10 to 49)': 'h_transportation_and_storage_small_10_to_49',
 'H : Transportation and storage Total': 'h_transportation_and_storage_total',
 'I : Accommodation and food service activities 0 to 4': 'i_accommodation_and_food_service_0_to_4',
 'I : Accommodation and food service activities 10 to 19': 'i_accommodation_and_food_service_10_to_19',
 'I : Accommodation and food service activities 100 to 249': 'i_accommodation_and_food_service_100_to_249',
 'I : Accommodation and food service activities 1000+': 'i_accommodation_and_food_service_1000plus',
 'I : Accommodation and food service activities 20 to 49': 'i_accommodation_and_food_service_20_to_49',
 'I : Accommodation and food service activities 250 to 499': 'i_accommodation_and_food_service_250_to_499',
 'I : Accommodation and food service activities 5 to 9': 'i_accommodation_and_food_service_5_to_9',
 'I : Accommodation and food service activities 50 to 99': 'i_accommodation_and_food_service_50_to_99',
 'I : Accommodation and food service activities 500 to 999': 'i_accommodation_and_food_service_500_to_999',
 'I : Accommodation and food service activities Large (250+)': 'i_accommodation_and_food_service_large_250plus',
 'I : Accommodation and food service activities Medium-sized (50 to 249)': 'i_accommodation_and_food_service_mediumsized_50_to_249',
 'I : Accommodation and food service activities Micro (0 to 9)': 'i_accommodation_and_food_service_micro_0_to_9',
 'I : Accommodation and food service activities Small (10 to 49)': 'i_accommodation_and_food_service_small_10_to_49',
 'I : Accommodation and food service activities Total': 'i_accommodation_and_food_service_total',
 'J : Information and communication 0 to 4': 'j_information_and_communication_0_to_4',
 'J : Information and communication 10 to 19': 'j_information_and_communication_10_to_19',
 'J : Information and communication 100 to 249': 'j_information_and_communication_100_to_249',
 'J : Information and communication 1000+': 'j_information_and_communication_1000plus',
 'J : Information and communication 20 to 49': 'j_information_and_communication_20_to_49',
 'J : Information and communication 250 to 499': 'j_information_and_communication_250_to_499',
 'J : Information and communication 5 to 9': 'j_information_and_communication_5_to_9',
 'J : Information and communication 50 to 99': 'j_information_and_communication_50_to_99',
 'J : Information and communication 500 to 999': 'j_information_and_communication_500_to_999',
 'J : Information and communication Large (250+)': 'j_information_and_communication_large_250plus',
 'J : Information and communication Medium-sized (50 to 249)': 'j_information_and_communication_mediumsized_50_to_249',
 'J : Information and communication Micro (0 to 9)': 'j_information_and_communication_micro_0_to_9',
 'J : Information and communication Small (10 to 49)': 'j_information_and_communication_small_10_to_49',
 'J : Information and communication Total': 'j_information_and_communication_total',
 'K : Financial and insurance activities 0 to 4': 'k_financial_and_insurance_activities_0_to_4',
 'K : Financial and insurance activities 10 to 19': 'k_financial_and_insurance_activities_10_to_19',
 'K : Financial and insurance activities 100 to 249': 'k_financial_and_insurance_activities_100_to_249',
 'K : Financial and insurance activities 1000+': 'k_financial_and_insurance_activities_1000plus',
 'K : Financial and insurance activities 20 to 49': 'k_financial_and_insurance_activities_20_to_49',
 'K : Financial and insurance activities 250 to 499': 'k_financial_and_insurance_activities_250_to_499',
 'K : Financial and insurance activities 5 to 9': 'k_financial_and_insurance_activities_5_to_9',
 'K : Financial and insurance activities 50 to 99': 'k_financial_and_insurance_activities_50_to_99',
 'K : Financial and insurance activities 500 to 999': 'k_financial_and_insurance_activities_500_to_999',
 'K : Financial and insurance activities Large (250+)': 'k_financial_and_insurance_activities_large_250plus',
 'K : Financial and insurance activities Medium-sized (50 to 249)': 'k_financial_and_insurance_activities_mediumsized_50_to_249',
 'K : Financial and insurance activities Micro (0 to 9)': 'k_financial_and_insurance_activities_micro_0_to_9',
 'K : Financial and insurance activities Small (10 to 49)': 'k_financial_and_insurance_activities_small_10_to_49',
 'K : Financial and insurance activities Total': 'k_financial_and_insurance_activities_total',
 'L : Real estate activities 0 to 4': 'l_real_estate_activities_0_to_4',
 'L : Real estate activities 10 to 19': 'l_real_estate_activities_10_to_19',
 'L : Real estate activities 100 to 249': 'l_real_estate_activities_100_to_249',
 'L : Real estate activities 1000+': 'l_real_estate_activities_1000plus',
 'L : Real estate activities 20 to 49': 'l_real_estate_activities_20_to_49',
 'L : Real estate activities 250 to 499': 'l_real_estate_activities_250_to_499',
 'L : Real estate activities 5 to 9': 'l_real_estate_activities_5_to_9',
 'L : Real estate activities 50 to 99': 'l_real_estate_activities_50_to_99',
 'L : Real estate activities 500 to 999': 'l_real_estate_activities_500_to_999',
 'L : Real estate activities Large (250+)': 'l_real_estate_activities_large_250plus',
 'L : Real estate activities Medium-sized (50 to 249)': 'l_real_estate_activities_mediumsized_50_to_249',
 'L : Real estate activities Micro (0 to 9)': 'l_real_estate_activities_micro_0_to_9',
 'L : Real estate activities Small (10 to 49)': 'l_real_estate_activities_small_10_to_49',
 'L : Real estate activities Total': 'l_real_estate_activities_total',
 'M : Professional, scientific and technical activities 0 to 4': 'm_scientific_and_technical_activities_0_to_4',
 'M : Professional, scientific and technical activities 10 to 19': 'm_scientific_and_technical_activities_10_to_19',
 'M : Professional, scientific and technical activities 100 to 249': 'm_scientific_and_technical_activities_100_to_249',
 'M : Professional, scientific and technical activities 1000+': 'm_scientific_and_technical_activities_1000plus',
 'M : Professional, scientific and technical activities 20 to 49': 'm_scientific_and_technical_activities_20_to_49',
 'M : Professional, scientific and technical activities 250 to 499': 'm_scientific_and_technical_activities_250_to_499',
 'M : Professional, scientific and technical activities 5 to 9': 'm_scientific_and_technical_activities_5_to_9',
 'M : Professional, scientific and technical activities 50 to 99': 'm_scientific_and_technical_activities_50_to_99',
 'M : Professional, scientific and technical activities 500 to 999': 'm_scientific_and_technical_activities_500_to_999',
 'M : Professional, scientific and technical activities Large (250+)': 'm_scientific_and_technical_activities_large_250plus',
 'M : Professional, scientific and technical activities Medium-sized (50 to 249)': 'm_scientific_and_technical_activities_mediumsized_50_to_249',
 'M : Professional, scientific and technical activities Micro (0 to 9)': 'm_scientific_and_technical_activities_micro_0_to_9',
 'M : Professional, scientific and technical activities Small (10 to 49)': 'm_scientific_and_technical_activities_small_10_to_49',
 'M : Professional, scientific and technical activities Total': 'm_scientific_and_technical_activities_total',
 'N : Administrative and support service activities 0 to 4': 'n_administrative_and_support_0_to_4',
 'N : Administrative and support service activities 10 to 19': 'n_administrative_and_support_10_to_19',
 'N : Administrative and support service activities 100 to 249': 'n_administrative_and_support_100_to_249',
 'N : Administrative and support service activities 1000+': 'n_administrative_and_support_1000plus',
 'N : Administrative and support service activities 20 to 49': 'n_administrative_and_support_20_to_49',
 'N : Administrative and support service activities 250 to 499': 'n_administrative_and_support_250_to_499',
 'N : Administrative and support service activities 5 to 9': 'n_administrative_and_support_5_to_9',
 'N : Administrative and support service activities 50 to 99': 'n_administrative_and_support_50_to_99',
 'N : Administrative and support service activities 500 to 999': 'n_administrative_and_support_500_to_999',
 'N : Administrative and support service activities Large (250+)': 'n_administrative_and_support_large_250plus',
 'N : Administrative and support service activities Medium-sized (50 to 249)': 'n_administrative_and_support_mediumsized_50_to_249',
 'N : Administrative and support service activities Micro (0 to 9)': 'n_administrative_and_support_micro_0_to_9',
 'N : Administrative and support service activities Small (10 to 49)': 'n_administrative_and_support_small_10_to_49',
 'N : Administrative and support service activities Total': 'n_administrative_and_support_total',
 'O : Public administration and defence; compulsory social security 0 to 4': 'o_public_admin_and_def_compulsory_ss_0_to_4',
 'O : Public administration and defence; compulsory social security 10 to 19': 'o_public_admin_and_def_compulsory_ss_10_to_19',
 'O : Public administration and defence; compulsory social security 100 to 249': 'o_public_admin_and_def_compulsory_ss_100_to_249',
 'O : Public administration and defence; compulsory social security 1000+': 'o_public_admin_and_def_compulsory_ss_1000plus',
 'O : Public administration and defence; compulsory social security 20 to 49': 'o_public_admin_and_def_compulsory_ss_20_to_49',
 'O : Public administration and defence; compulsory social security 250 to 499': 'o_public_admin_and_def_compulsory_ss_250_to_499',
 'O : Public administration and defence; compulsory social security 5 to 9': 'o_public_admin_and_def_compulsory_ss_5_to_9',
 'O : Public administration and defence; compulsory social security 50 to 99': 'o_public_admin_and_def_compulsory_ss_50_to_99',
 'O : Public administration and defence; compulsory social security 500 to 999': 'o_public_admin_and_def_compulsory_ss_500_to_999',
 'O : Public administration and defence; compulsory social security Large (250+)': 'o_public_admin_and_def_compulsory_ss_large_250plus',
 'O : Public administration and defence; compulsory social security Medium-sized (50 to 249)': 'o_public_admin_and_def_compulsory_ss_mediumsized_50_to_249',
 'O : Public administration and defence; compulsory social security Micro (0 to 9)': 'o_public_admin_and_def_compulsory_ss_micro_0_to_9',
 'O : Public administration and defence; compulsory social security Small (10 to 49)': 'o_public_admin_and_def_compulsory_ss_small_10_to_49',
 'O : Public administration and defence; compulsory social security Total': 'o_public_admin_and_def_compulsory_ss_total',
 'P : Education 0 to 4': 'p_education_0_to_4',
 'P : Education 10 to 19': 'p_education_10_to_19',
 'P : Education 100 to 249': 'p_education_100_to_249',
 'P : Education 1000+': 'p_education_1000plus',
 'P : Education 20 to 49': 'p_education_20_to_49',
 'P : Education 250 to 499': 'p_education_250_to_499',
 'P : Education 5 to 9': 'p_education_5_to_9',
 'P : Education 50 to 99': 'p_education_50_to_99',
 'P : Education 500 to 999': 'p_education_500_to_999',
 'P : Education Large (250+)': 'p_education_large_250plus',
 'P : Education Medium-sized (50 to 249)': 'p_education_mediumsized_50_to_249',
 'P : Education Micro (0 to 9)': 'p_education_micro_0_to_9',
 'P : Education Small (10 to 49)': 'p_education_small_10_to_49',
 'P : Education Total': 'p_education_total',
 'Q : Human health and social work activities 0 to 4': 'q_human_health_and_social_work_0_to_4',
 'Q : Human health and social work activities 10 to 19': 'q_human_health_and_social_work_10_to_19',
 'Q : Human health and social work activities 100 to 249': 'q_human_health_and_social_work_100_to_249',
 'Q : Human health and social work activities 1000+': 'q_human_health_and_social_work_1000plus',
 'Q : Human health and social work activities 20 to 49': 'q_human_health_and_social_work_20_to_49',
 'Q : Human health and social work activities 250 to 499': 'q_human_health_and_social_work_250_to_499',
 'Q : Human health and social work activities 5 to 9': 'q_human_health_and_social_work_5_to_9',
 'Q : Human health and social work activities 50 to 99': 'q_human_health_and_social_work_50_to_99',
 'Q : Human health and social work activities 500 to 999': 'q_human_health_and_social_work_500_to_999',
 'Q : Human health and social work activities Large (250+)': 'q_human_health_and_social_work_large_250plus',
 'Q : Human health and social work activities Medium-sized (50 to 249)': 'q_human_health_and_social_work_mediumsized_50_to_249',
 'Q : Human health and social work activities Micro (0 to 9)': 'q_human_health_and_social_work_micro_0_to_9',
 'Q : Human health and social work activities Small (10 to 49)': 'q_human_health_and_social_work_small_10_to_49',
 'Q : Human health and social work activities Total': 'q_human_health_and_social_work_total',
 'R : Arts, entertainment and recreation 0 to 4': 'r_arts_entertainment_and_recreation_0_to_4',
 'R : Arts, entertainment and recreation 10 to 19': 'r_arts_entertainment_and_recreation_10_to_19',
 'R : Arts, entertainment and recreation 100 to 249': 'r_arts_entertainment_and_recreation_100_to_249',
 'R : Arts, entertainment and recreation 1000+': 'r_arts_entertainment_and_recreation_1000plus',
 'R : Arts, entertainment and recreation 20 to 49': 'r_arts_entertainment_and_recreation_20_to_49',
 'R : Arts, entertainment and recreation 250 to 499': 'r_arts_entertainment_and_recreation_250_to_499',
 'R : Arts, entertainment and recreation 5 to 9': 'r_arts_entertainment_and_recreation_5_to_9',
 'R : Arts, entertainment and recreation 50 to 99': 'r_arts_entertainment_and_recreation_50_to_99',
 'R : Arts, entertainment and recreation 500 to 999': 'r_arts_entertainment_and_recreation_500_to_999',
 'R : Arts, entertainment and recreation Large (250+)': 'r_arts_entertainment_and_recreation_large_250plus',
 'R : Arts, entertainment and recreation Medium-sized (50 to 249)': 'r_arts_entertainment_and_recreation_mediumsized_50_to_249',
 'R : Arts, entertainment and recreation Micro (0 to 9)': 'r_arts_entertainment_and_recreation_micro_0_to_9',
 'R : Arts, entertainment and recreation Small (10 to 49)': 'r_arts_entertainment_and_recreation_small_10_to_49',
 'R : Arts, entertainment and recreation Total': 'r_arts_entertainment_and_recreation_total',
 'S : Other service activities 0 to 4': 's_other_service_activities_0_to_4',
 'S : Other service activities 10 to 19': 's_other_service_activities_10_to_19',
 'S : Other service activities 100 to 249': 's_other_service_activities_100_to_249',
 'S : Other service activities 1000+': 's_other_service_activities_1000plus',
 'S : Other service activities 20 to 49': 's_other_service_activities_20_to_49',
 'S : Other service activities 250 to 499': 's_other_service_activities_250_to_499',
 'S : Other service activities 5 to 9': 's_other_service_activities_5_to_9',
 'S : Other service activities 50 to 99': 's_other_service_activities_50_to_99',
 'S : Other service activities 500 to 999': 's_other_service_activities_500_to_999',
 'S : Other service activities Large (250+)': 's_other_service_activities_large_250plus',
 'S : Other service activities Medium-sized (50 to 249)': 's_other_service_activities_mediumsized_50_to_249',
 'S : Other service activities Micro (0 to 9)': 's_other_service_activities_micro_0_to_9',
 'S : Other service activities Small (10 to 49)': 's_other_service_activities_small_10_to_49',
 'S : Other service activities Total': 's_other_service_activities_total',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 0 to 4': 't_econ_activity_households_for_own_use_0_to_4',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 10 to 19': 't_econ_activity_households_for_own_use_10_to_19',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 100 to 249': 't_econ_activity_households_for_own_use_100_to_249',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 1000+': 't_econ_activity_households_for_own_use_1000plus',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 20 to 49': 't_econ_activity_households_for_own_use_20_to_49',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 250 to 499': 't_econ_activity_households_for_own_use_250_to_499',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 5 to 9': 't_econ_activity_households_for_own_use_5_to_9',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 50 to 99': 't_econ_activity_households_for_own_use_50_to_99',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use 500 to 999': 't_econ_activity_households_for_own_use_500_to_999',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Large (250+)': 't_econ_activity_households_for_own_use_large_250plus',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Medium-sized (50 to 249)': 't_econ_activity_households_for_own_use_mediumsized_50_to_249',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Micro (0 to 9)': 't_econ_activity_households_for_own_use_micro_0_to_9',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Small (10 to 49)': 't_econ_activity_households_for_own_use_small_10_to_49',
 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use Total': 't_econ_activity_households_for_own_use_total',
 'U : Activities of extraterritorial organisations and bodies 0 to 4': 'u_extraterr_orgs_and_bodies_0_to_4',
 'U : Activities of extraterritorial organisations and bodies 10 to 19': 'u_extraterr_orgs_and_bodies_10_to_19',
 'U : Activities of extraterritorial organisations and bodies 100 to 249': 'u_extraterr_orgs_and_bodies_100_to_249',
 'U : Activities of extraterritorial organisations and bodies 1000+': 'u_extraterr_orgs_and_bodies_1000plus',
 'U : Activities of extraterritorial organisations and bodies 20 to 49': 'u_extraterr_orgs_and_bodies_20_to_49',
 'U : Activities of extraterritorial organisations and bodies 250 to 499': 'u_extraterr_orgs_and_bodies_250_to_499',
 'U : Activities of extraterritorial organisations and bodies 5 to 9': 'u_extraterr_orgs_and_bodies_5_to_9',
 'U : Activities of extraterritorial organisations and bodies 50 to 99': 'u_extraterr_orgs_and_bodies_50_to_99',
 'U : Activities of extraterritorial organisations and bodies 500 to 999': 'u_extraterr_orgs_and_bodies_500_to_999',
 'U : Activities of extraterritorial organisations and bodies Large (250+)': 'u_extraterr_orgs_and_bodies_large_250plus',
 'U : Activities of extraterritorial organisations and bodies Medium-sized (50 to 249)': 'u_extraterr_orgs_and_bodies_mediumsized_50_to_249',
 'U : Activities of extraterritorial organisations and bodies Micro (0 to 9)': 'u_extraterr_orgs_and_bodies_micro_0_to_9',
 'U : Activities of extraterritorial organisations and bodies Small (10 to 49)': 'u_extraterr_orgs_and_bodies_small_10_to_49',
 'U : Activities of extraterritorial organisations and bodies Total': 'u_extraterr_orgs_and_bodies_total'}

business_register_reformat = {
    '01 : Crop and animal production, hunting and related service activities Employees': '01_crop_and_animal_production_hunting_employees',
 '01 : Crop and animal production, hunting and related service activities Full-time employees': '01_crop_and_animal_production_hunting_fulltime_employees',
 '01 : Crop and animal production, hunting and related service activities Part-time employees': '01_crop_and_animal_production_hunting_parttime_employees',
 '02 : Forestry and logging Employees': '02_forestry_and_logging_employees',
 '02 : Forestry and logging Full-time employees': '02_forestry_and_logging_fulltime_employees',
 '02 : Forestry and logging Part-time employees': '02_forestry_and_logging_parttime_employees',
 '03 : Fishing and aquaculture Employees': '03_fishing_and_aquaculture_employees',
 '03 : Fishing and aquaculture Full-time employees': '03_fishing_and_aquaculture_fulltime_employees',
 '03 : Fishing and aquaculture Part-time employees': '03_fishing_and_aquaculture_parttime_employees',
 '05 : Mining of coal and lignite Employees': '05_mining_of_coal_and_lignite_employees',
 '05 : Mining of coal and lignite Full-time employees': '05_mining_of_coal_and_lignite_fulltime_employees',
 '05 : Mining of coal and lignite Part-time employees': '05_mining_of_coal_and_lignite_parttime_employees',
 '06 : Extraction of crude petroleum and natural gas Employees': '06_extraction_of_crude_oil_and_natgas_employees',
 '06 : Extraction of crude petroleum and natural gas Full-time employees': '06_extraction_of_crude_oil_and_natgas_fulltime_employees',
 '06 : Extraction of crude petroleum and natural gas Part-time employees': '06_extraction_of_crude_oil_and_natgas_parttime_employees',
 '07 : Mining of metal ores Employees': '07_mining_of_metal_ores_employees',
 '07 : Mining of metal ores Full-time employees': '07_mining_of_metal_ores_fulltime_employees',
 '07 : Mining of metal ores Part-time employees': '07_mining_of_metal_ores_parttime_employees',
 '08 : Other mining and quarrying Employees': '08_other_mining_and_quarrying_employees',
 '08 : Other mining and quarrying Full-time employees': '08_other_mining_and_quarrying_fulltime_employees',
 '08 : Other mining and quarrying Part-time employees': '08_other_mining_and_quarrying_parttime_employees',
 '09 : Mining support service activities Employees': '09_mining_support_service_activities_employees',
 '09 : Mining support service activities Full-time employees': '09_mining_support_service_activities_fulltime_employees',
 '09 : Mining support service activities Part-time employees': '09_mining_support_service_activities_parttime_employees',
 '10 : Manufacture of food products Employees': '10_manufacture_of_food_products_employees',
 '10 : Manufacture of food products Full-time employees': '10_manufacture_of_food_products_fulltime_employees',
 '10 : Manufacture of food products Part-time employees': '10_manufacture_of_food_products_parttime_employees',
 '11 : Manufacture of beverages Employees': '11_manufacture_of_beverages_employees',
 '11 : Manufacture of beverages Full-time employees': '11_manufacture_of_beverages_fulltime_employees',
 '11 : Manufacture of beverages Part-time employees': '11_manufacture_of_beverages_parttime_employees',
 '12 : Manufacture of tobacco products Employees': '12_manufacture_of_tobacco_products_employees',
 '12 : Manufacture of tobacco products Full-time employees': '12_manufacture_of_tobacco_products_fulltime_employees',
 '12 : Manufacture of tobacco products Part-time employees': '12_manufacture_of_tobacco_products_parttime_employees',
 '13 : Manufacture of textiles Employees': '13_manufacture_of_textiles_employees',
 '13 : Manufacture of textiles Full-time employees': '13_manufacture_of_textiles_fulltime_employees',
 '13 : Manufacture of textiles Part-time employees': '13_manufacture_of_textiles_parttime_employees',
 '14 : Manufacture of wearing apparel Employees': '14_manufacture_of_wearing_apparel_employees',
 '14 : Manufacture of wearing apparel Full-time employees': '14_manufacture_of_wearing_apparel_fulltime_employees',
 '14 : Manufacture of wearing apparel Part-time employees': '14_manufacture_of_wearing_apparel_parttime_employees',
 '15 : Manufacture of leather and related products Employees': '15_manufacture_of_leather_employees',
 '15 : Manufacture of leather and related products Full-time employees': '15_manufacture_of_leather_fulltime_employees',
 '15 : Manufacture of leather and related products Part-time employees': '15_manufacture_of_leather_parttime_employees',
 '16 : Manufacture of wood and of products of wood and cork, except furniture;manufacture of articles of straw and plaiting materials Employees': '16_manufacture_of_wood_excl_furniture_employees',
 '16 : Manufacture of wood and of products of wood and cork, except furniture;manufacture of articles of straw and plaiting materials Full-time employees': '16_manufacture_of_wood_excl_furniture_fulltime_employees',
 '16 : Manufacture of wood and of products of wood and cork, except furniture;manufacture of articles of straw and plaiting materials Part-time employees': '16_manufacture_of_wood_excl_furniture_parttime_employees',
 '17 : Manufacture of paper and paper products Employees': '17_manufacture_of_paper_and_paper_products_employees',
 '17 : Manufacture of paper and paper products Full-time employees': '17_manufacture_of_paper_and_paper_products_fulltime_employees',
 '17 : Manufacture of paper and paper products Part-time employees': '17_manufacture_of_paper_and_paper_products_parttime_employees',
 '18 : Printing and reproduction of recorded media Employees': '18_print_and_repr_of_recorded_media_employees',
 '18 : Printing and reproduction of recorded media Full-time employees': '18_print_and_repr_of_recorded_media_fulltime_employees',
 '18 : Printing and reproduction of recorded media Part-time employees': '18_print_and_repr_of_recorded_media_parttime_employees',
 '19 : Manufacture of coke and refined petroleum products Employees': '19_manufacture_of_coke_and_refined_oil_employees',
 '19 : Manufacture of coke and refined petroleum products Full-time employees': '19_manufacture_of_coke_and_refined_oil_fulltime_employees',
 '19 : Manufacture of coke and refined petroleum products Part-time employees': '19_manufacture_of_coke_and_refined_oil_parttime_employees',
 '20 : Manufacture of chemicals and chemical products Employees': '20_manufacture_of_chems_and_products_employees',
 '20 : Manufacture of chemicals and chemical products Full-time employees': '20_manufacture_of_chems_and_products_fulltime_employees',
 '20 : Manufacture of chemicals and chemical products Part-time employees': '20_manufacture_of_chems_and_products_parttime_employees',
 '21 : Manufacture of basic pharmaceutical products and pharmaceutical preparations Employees': '21_manufacture_of_basic_pharm_prods_employees',
 '21 : Manufacture of basic pharmaceutical products and pharmaceutical preparations Full-time employees': '21_manufacture_of_basic_pharm_prods_fulltime_employees',
 '21 : Manufacture of basic pharmaceutical products and pharmaceutical preparations Part-time employees': '21_manufacture_of_basic_pharm_prods_parttime_employees',
 '22 : Manufacture of rubber and plastic products Employees': '22_manufacture_of_rubber_and_plastic_prods_employees',
 '22 : Manufacture of rubber and plastic products Full-time employees': '22_manufacture_of_rubber_and_plastic_prods_fulltime_employees',
 '22 : Manufacture of rubber and plastic products Part-time employees': '22_manufacture_of_rubber_and_plastic_prods_parttime_employees',
 '23 : Manufacture of other non-metallic mineral products Employees': '23_manufacture_of_other_mineral_products_employees',
 '23 : Manufacture of other non-metallic mineral products Full-time employees': '23_manufacture_of_other_mineral_products_fulltime_employees',
 '23 : Manufacture of other non-metallic mineral products Part-time employees': '23_manufacture_of_other_mineral_products_parttime_employees',
 '24 : Manufacture of basic metals Employees': '24_manufacture_of_basic_metals_employees',
 '24 : Manufacture of basic metals Full-time employees': '24_manufacture_of_basic_metals_fulltime_employees',
 '24 : Manufacture of basic metals Part-time employees': '24_manufacture_of_basic_metals_parttime_employees',
 '25 : Manufacture of fabricated metal products, except machinery and equipment Employees': '25_manufacture_of_fabr_metal_products_employees',
 '25 : Manufacture of fabricated metal products, except machinery and equipment Full-time employees': '25_manufacture_of_fabr_metal_products_fulltime_employees',
 '25 : Manufacture of fabricated metal products, except machinery and equipment Part-time employees': '25_manufacture_of_fabr_metal_products_parttime_employees',
 '26 : Manufacture of computer, electronic and optical products Employees': '26_manufacture_of_comp_electronics_optics_employees',
 '26 : Manufacture of computer, electronic and optical products Full-time employees': '26_manufacture_of_comp_electronics_optics_fulltime_employees',
 '26 : Manufacture of computer, electronic and optical products Part-time employees': '26_manufacture_of_comp_electronics_optics_parttime_employees',
 '27 : Manufacture of electrical equipment Employees': '27_manufacture_of_electrical_equipment_employees',
 '27 : Manufacture of electrical equipment Full-time employees': '27_manufacture_of_electrical_equipment_fulltime_employees',
 '27 : Manufacture of electrical equipment Part-time employees': '27_manufacture_of_electrical_equipment_parttime_employees',
 '28 : Manufacture of machinery and equipment n.e.c. Employees': '28_manufacture_of_machinery_and_equipment_employees',
 '28 : Manufacture of machinery and equipment n.e.c. Full-time employees': '28_manufacture_of_machinery_and_equipment_fulltime_employees',
 '28 : Manufacture of machinery and equipment n.e.c. Part-time employees': '28_manufacture_of_machinery_and_equipment_parttime_employees',
 '29 : Manufacture of motor vehicles, trailers and semi-trailers Employees': '29_manufacture_of_motor_vehicles_trailers_employees',
 '29 : Manufacture of motor vehicles, trailers and semi-trailers Full-time employees': '29_manufacture_of_motor_vehicles_trailers_fulltime_employees',
 '29 : Manufacture of motor vehicles, trailers and semi-trailers Part-time employees': '29_manufacture_of_motor_vehicles_trailers_parttime_employees',
 '30 : Manufacture of other transport equipment Employees': '30_manufacture_of_other_transport_equip_employees',
 '30 : Manufacture of other transport equipment Full-time employees': '30_manufacture_of_other_transport_equip_fulltime_employees',
 '30 : Manufacture of other transport equipment Part-time employees': '30_manufacture_of_other_transport_equip_parttime_employees',
 '31 : Manufacture of furniture Employees': '31_manufacture_of_furniture_employees',
 '31 : Manufacture of furniture Full-time employees': '31_manufacture_of_furniture_fulltime_employees',
 '31 : Manufacture of furniture Part-time employees': '31_manufacture_of_furniture_parttime_employees',
 '32 : Other manufacturing Employees': '32_other_manufacturing_employees',
 '32 : Other manufacturing Full-time employees': '32_other_manufacturing_fulltime_employees',
 '32 : Other manufacturing Part-time employees': '32_other_manufacturing_parttime_employees',
 '33 : Repair and installation of machinery and equipment Employees': '33_repair_and_installation_of_machinery_employees',
 '33 : Repair and installation of machinery and equipment Full-time employees': '33_repair_and_installation_of_machinery_fulltime_employees',
 '33 : Repair and installation of machinery and equipment Part-time employees': '33_repair_and_installation_of_machinery_parttime_employees',
 '35 : Electricity, gas, steam and air conditioning supply Employees': '35_electricity_gas_air_conditioning_supply_employees',
 '35 : Electricity, gas, steam and air conditioning supply Full-time employees': '35_electricity_gas_air_conditioning_supply_fulltime_employees',
 '35 : Electricity, gas, steam and air conditioning supply Part-time employees': '35_electricity_gas_air_conditioning_supply_parttime_employees',
 '36 : Water collection, treatment and supply Employees': '36_water_collection_treatment_and_supply_employees',
 '36 : Water collection, treatment and supply Full-time employees': '36_water_collection_treatment_and_supply_fulltime_employees',
 '36 : Water collection, treatment and supply Part-time employees': '36_water_collection_treatment_and_supply_parttime_employees',
 '37 : Sewerage Employees': '37_sewerage_employees',
 '37 : Sewerage Full-time employees': '37_sewerage_fulltime_employees',
 '37 : Sewerage Part-time employees': '37_sewerage_parttime_employees',
 '38 : Waste collection, treatment and disposal activities; materials recovery Employees': '38_waste_collection_disposal_activities_employees',
 '38 : Waste collection, treatment and disposal activities; materials recovery Full-time employees': '38_waste_collection_disposal_activities_fulltime_employees',
 '38 : Waste collection, treatment and disposal activities; materials recovery Part-time employees': '38_waste_collection_disposal_activities_parttime_employees',
 '39 : Remediation activities and other waste management services. This division includes the provision of remediation services, i.e. the cleanup of contaminated buildings and sites, soil, surface or ground water. Employees': '39_other_waste_management_services_employees',
 '39 : Remediation activities and other waste management services. This division includes the provision of remediation services, i.e. the cleanup of contaminated buildings and sites, soil, surface or ground water. Full-time employees': '39_other_waste_management_services_fulltime_employees',
 '39 : Remediation activities and other waste management services. This division includes the provision of remediation services, i.e. the cleanup of contaminated buildings and sites, soil, surface or ground water. Part-time employees': '39_other_waste_management_services_parttime_employees',
 '41 : Construction of buildings Employees': '41_construction_of_buildings_employees',
 '41 : Construction of buildings Full-time employees': '41_construction_of_buildings_fulltime_employees',
 '41 : Construction of buildings Part-time employees': '41_construction_of_buildings_parttime_employees',
 '42 : Civil engineering Employees': '42_civil_engineering_employees',
 '42 : Civil engineering Full-time employees': '42_civil_engineering_fulltime_employees',
 '42 : Civil engineering Part-time employees': '42_civil_engineering_parttime_employees',
 '43 : Specialised construction activities Employees': '43_specialised_construction_activities_employees',
 '43 : Specialised construction activities Full-time employees': '43_specialised_construction_activities_fulltime_employees',
 '43 : Specialised construction activities Part-time employees': '43_specialised_construction_activities_parttime_employees',
 '45 : Wholesale and retail trade and repair of motor vehicles and motorcycles Employees': '45_trade_and_repair_of_motor_vehicles_employees',
 '45 : Wholesale and retail trade and repair of motor vehicles and motorcycles Full-time employees': '45_trade_and_repair_of_motor_vehicles_fulltime_employees',
 '45 : Wholesale and retail trade and repair of motor vehicles and motorcycles Part-time employees': '45_trade_and_repair_of_motor_vehicles_parttime_employees',
 '46 : Wholesale trade, except of motor vehicles and motorcycles Employees': '46_wholesale_trade_except_motor_vehicles_employees',
 '46 : Wholesale trade, except of motor vehicles and motorcycles Full-time employees': '46_wholesale_trade_except_motor_vehicles_fulltime_employees',
 '46 : Wholesale trade, except of motor vehicles and motorcycles Part-time employees': '46_wholesale_trade_except_motor_vehicles_parttime_employees',
 '47 : Retail trade, except of motor vehicles and motorcycles Employees': '47_retail_trade_except_motor_vehicles_employees',
 '47 : Retail trade, except of motor vehicles and motorcycles Full-time employees': '47_retail_trade_except_motor_vehicles_fulltime_employees',
 '47 : Retail trade, except of motor vehicles and motorcycles Part-time employees': '47_retail_trade_except_motor_vehicles_parttime_employees',
 '49 : Land transport and transport via pipelines Employees': '49_land_and_pipeline_transport_employees',
 '49 : Land transport and transport via pipelines Full-time employees': '49_land_and_pipeline_transport_fulltime_employees',
 '49 : Land transport and transport via pipelines Part-time employees': '49_land_and_pipeline_transport_parttime_employees',
 '50 : Water transport Employees': '50_water_transport_employees',
 '50 : Water transport Full-time employees': '50_water_transport_fulltime_employees',
 '50 : Water transport Part-time employees': '50_water_transport_parttime_employees',
 '51 : Air transport Employees': '51_air_transport_employees',
 '51 : Air transport Full-time employees': '51_air_transport_fulltime_employees',
 '51 : Air transport Part-time employees': '51_air_transport_parttime_employees',
 '52 : Warehousing and support activities for transportation Employees': '52_warehousing_and_support_for_transport_employees',
 '52 : Warehousing and support activities for transportation Full-time employees': '52_warehousing_and_support_for_transport_fulltime_employees',
 '52 : Warehousing and support activities for transportation Part-time employees': '52_warehousing_and_support_for_transport_parttime_employees',
 '53 : Postal and courier activities Employees': '53_postal_and_courier_activities_employees',
 '53 : Postal and courier activities Full-time employees': '53_postal_and_courier_activities_fulltime_employees',
 '53 : Postal and courier activities Part-time employees': '53_postal_and_courier_activities_parttime_employees',
 '55 : Accommodation Employees': '55_accommodation_employees',
 '55 : Accommodation Full-time employees': '55_accommodation_fulltime_employees',
 '55 : Accommodation Part-time employees': '55_accommodation_parttime_employees',
 '56 : Food and beverage service activities Employees': '56_food_and_beverage_service_activities_employees',
 '56 : Food and beverage service activities Full-time employees': '56_food_and_beverage_service_activities_fulltime_employees',
 '56 : Food and beverage service activities Part-time employees': '56_food_and_beverage_service_activities_parttime_employees',
 '58 : Publishing activities Employees': '58_publishing_activities_employees',
 '58 : Publishing activities Full-time employees': '58_publishing_activities_fulltime_employees',
 '58 : Publishing activities Part-time employees': '58_publishing_activities_parttime_employees',
 '59 : Motion picture, video and television programme production, sound recording and music publishing activities Employees': '59_video_audio_production_employees',
 '59 : Motion picture, video and television programme production, sound recording and music publishing activities Full-time employees': '59_video_audio_production_fulltime_employees',
 '59 : Motion picture, video and television programme production, sound recording and music publishing activities Part-time employees': '59_video_audio_production_parttime_employees',
 '60 : Programming and broadcasting activities Employees': '60_programming_and_broadcasting_activities_employees',
 '60 : Programming and broadcasting activities Full-time employees': '60_programming_and_broadcasting_activities_fulltime_employees',
 '60 : Programming and broadcasting activities Part-time employees': '60_programming_and_broadcasting_activities_parttime_employees',
 '61 : Telecommunications Employees': '61_telecommunications_employees',
 '61 : Telecommunications Full-time employees': '61_telecommunications_fulltime_employees',
 '61 : Telecommunications Part-time employees': '61_telecommunications_parttime_employees',
 '62 : Computer programming, consultancy and related activities Employees': '62_it_consultancy_employees',
 '62 : Computer programming, consultancy and related activities Full-time employees': '62_it_consultancy_fulltime_employees',
 '62 : Computer programming, consultancy and related activities Part-time employees': '62_it_consultancy_parttime_employees',
 '63 : Information service activities Employees': '63_information_service_activities_employees',
 '63 : Information service activities Full-time employees': '63_information_service_activities_fulltime_employees',
 '63 : Information service activities Part-time employees': '63_information_service_activities_parttime_employees',
 '64 : Financial service activities, except insurance and pension funding Employees': '64_finance_except_insurance_and_pensions_employees',
 '64 : Financial service activities, except insurance and pension funding Full-time employees': '64_finance_except_insurance_and_pensions_fulltime_employees',
 '64 : Financial service activities, except insurance and pension funding Part-time employees': '64_finance_except_insurance_and_pensions_parttime_employees',
 '65 : Insurance, reinsurance and pension funding, except compulsory social security Employees': '65_insurance_pension_except_compulsory_ss_employees',
 '65 : Insurance, reinsurance and pension funding, except compulsory social security Full-time employees': '65_insurance_pension_except_compulsory_ss_fulltime_employees',
 '65 : Insurance, reinsurance and pension funding, except compulsory social security Part-time employees': '65_insurance_pension_except_compulsory_ss_parttime_employees',
 '66 : Activities auxiliary to financial services and insurance activities Employees': '66_auxilliary_activity_finance_employees',
 '66 : Activities auxiliary to financial services and insurance activities Full-time employees': '66_auxilliary_activity_finance_fulltime_employees',
 '66 : Activities auxiliary to financial services and insurance activities Part-time employees': '66_auxilliary_activity_finance_parttime_employees',
 '68 : Real estate activities Employees': '68_real_estate_activities_employees',
 '68 : Real estate activities Full-time employees': '68_real_estate_activities_fulltime_employees',
 '68 : Real estate activities Part-time employees': '68_real_estate_activities_parttime_employees',
 '69 : Legal and accounting activities Employees': '69_legal_and_accounting_activities_employees',
 '69 : Legal and accounting activities Full-time employees': '69_legal_and_accounting_activities_fulltime_employees',
 '69 : Legal and accounting activities Part-time employees': '69_legal_and_accounting_activities_parttime_employees',
 '70 : Activities of head offices; management consultancy activities Employees': '70_management_consultancy_employees',
 '70 : Activities of head offices; management consultancy activities Full-time employees': '70_management_consultancy_fulltime_employees',
 '70 : Activities of head offices; management consultancy activities Part-time employees': '70_management_consultancy_parttime_employees',
 '71 : Architectural and engineering activities; technical testing and analysis Employees': '71_architecture_and_engineering_employees',
 '71 : Architectural and engineering activities; technical testing and analysis Full-time employees': '71_architecture_and_engineering_fulltime_employees',
 '71 : Architectural and engineering activities; technical testing and analysis Part-time employees': '71_architecture_and_engineering_parttime_employees',
 '72 : Scientific research and development Employees': '72_scientific_research_and_development_employees',
 '72 : Scientific research and development Full-time employees': '72_scientific_research_and_development_fulltime_employees',
 '72 : Scientific research and development Part-time employees': '72_scientific_research_and_development_parttime_employees',
 '73 : Advertising and market research Employees': '73_advertising_and_market_research_employees',
 '73 : Advertising and market research Full-time employees': '73_advertising_and_market_research_fulltime_employees',
 '73 : Advertising and market research Part-time employees': '73_advertising_and_market_research_parttime_employees',
 '74 : Other professional, scientific and technical activities Employees': '74_other_scientific_technical_activities_employees',
 '74 : Other professional, scientific and technical activities Full-time employees': '74_other_scientific_technical_activities_fulltime_employees',
 '74 : Other professional, scientific and technical activities Part-time employees': '74_other_scientific_technical_activities_parttime_employees',
 '75 : Veterinary activities Employees': '75_veterinary_activities_employees',
 '75 : Veterinary activities Full-time employees': '75_veterinary_activities_fulltime_employees',
 '75 : Veterinary activities Part-time employees': '75_veterinary_activities_parttime_employees',
 '77 : Rental and leasing activities Employees': '77_rental_and_leasing_activities_employees',
 '77 : Rental and leasing activities Full-time employees': '77_rental_and_leasing_activities_fulltime_employees',
 '77 : Rental and leasing activities Part-time employees': '77_rental_and_leasing_activities_parttime_employees',
 '78 : Employment activities Employees': '78_employment_activities_employees',
 '78 : Employment activities Full-time employees': '78_employment_activities_fulltime_employees',
 '78 : Employment activities Part-time employees': '78_employment_activities_parttime_employees',
 '79 : Travel agency, tour operator and other reservation service and related activities Employees': '79_travel_agency_and_related_activities_employees',
 '79 : Travel agency, tour operator and other reservation service and related activities Full-time employees': '79_travel_agency_and_related_activities_fulltime_employees',
 '79 : Travel agency, tour operator and other reservation service and related activities Part-time employees': '79_travel_agency_and_related_activities_parttime_employees',
 '80 : Security and investigation activities Employees': '80_security_and_investigation_activities_employees',
 '80 : Security and investigation activities Full-time employees': '80_security_and_investigation_activities_fulltime_employees',
 '80 : Security and investigation activities Part-time employees': '80_security_and_investigation_activities_parttime_employees',
 '81 : Services to buildings and landscape activities Employees': '81_buildings_and_landscape_service_employees',
 '81 : Services to buildings and landscape activities Full-time employees': '81_buildings_and_landscape_service_fulltime_employees',
 '81 : Services to buildings and landscape activities Part-time employees': '81_buildings_and_landscape_service_parttime_employees',
 '82 : Office administrative, office support and other business support activities Employees': '82_office_and_business_support_employees',
 '82 : Office administrative, office support and other business support activities Full-time employees': '82_office_and_business_support_fulltime_employees',
 '82 : Office administrative, office support and other business support activities Part-time employees': '82_office_and_business_support_parttime_employees',
 '84 : Public administration and defence; compulsory social security Employees': '84_public_admin_and_def_compulsory_ss_employees',
 '84 : Public administration and defence; compulsory social security Full-time employees': '84_public_admin_and_def_compulsory_ss_fulltime_employees',
 '84 : Public administration and defence; compulsory social security Part-time employees': '84_public_admin_and_def_compulsory_ss_parttime_employees',
 '85 : Education Employees': '85_education_employees',
 '85 : Education Full-time employees': '85_education_fulltime_employees',
 '85 : Education Part-time employees': '85_education_parttime_employees',
 '86 : Human health activities Employees': '86_human_health_activities_employees',
 '86 : Human health activities Full-time employees': '86_human_health_activities_fulltime_employees',
 '86 : Human health activities Part-time employees': '86_human_health_activities_parttime_employees',
 '87 : Residential care activities Employees': '87_residential_care_activities_employees',
 '87 : Residential care activities Full-time employees': '87_residential_care_activities_fulltime_employees',
 '87 : Residential care activities Part-time employees': '87_residential_care_activities_parttime_employees',
 '88 : Social work activities without accommodation Employees': '88_social_work_without_accommod_employees',
 '88 : Social work activities without accommodation Full-time employees': '88_social_work_without_accommod_fulltime_employees',
 '88 : Social work activities without accommodation Part-time employees': '88_social_work_without_accommod_parttime_employees',
 '90 : Creative, arts and entertainment activities Employees': '90_arts_and_entertainment_employees',
 '90 : Creative, arts and entertainment activities Full-time employees': '90_arts_and_entertainment_fulltime_employees',
 '90 : Creative, arts and entertainment activities Part-time employees': '90_arts_and_entertainment_parttime_employees',
 '91 : Libraries, archives, museums and other cultural activities Employees': '91_libraries_museums_other_culture_employees',
 '91 : Libraries, archives, museums and other cultural activities Full-time employees': '91_libraries_museums_other_culture_fulltime_employees',
 '91 : Libraries, archives, museums and other cultural activities Part-time employees': '91_libraries_museums_other_culture_parttime_employees',
 '92 : Gambling and betting activities Employees': '92_gambling_and_betting_activities_employees',
 '92 : Gambling and betting activities Full-time employees': '92_gambling_and_betting_activities_fulltime_employees',
 '92 : Gambling and betting activities Part-time employees': '92_gambling_and_betting_activities_parttime_employees',
 '93 : Sports activities and amusement and recreation activities Employees': '93_sports_amusement_recreation_employees',
 '93 : Sports activities and amusement and recreation activities Full-time employees': '93_sports_amusement_recreation_fulltime_employees',
 '93 : Sports activities and amusement and recreation activities Part-time employees': '93_sports_amusement_recreation_parttime_employees',
 '94 : Activities of membership organisations Employees': '94_activities_of_membership_organisations_employees',
 '94 : Activities of membership organisations Full-time employees': '94_activities_of_membership_organisations_fulltime_employees',
 '94 : Activities of membership organisations Part-time employees': '94_activities_of_membership_organisations_parttime_employees',
 '95 : Repair of computers and personal and household goods Employees': '95_repair_personal_goods_employees',
 '95 : Repair of computers and personal and household goods Full-time employees': '95_repair_personal_goods_fulltime_employees',
 '95 : Repair of computers and personal and household goods Part-time employees': '95_repair_personal_goods_parttime_employees',
 '96 : Other personal service activities Employees': '96_other_personal_service_activities_employees',
 '96 : Other personal service activities Full-time employees': '96_other_personal_service_activities_fulltime_employees',
 '96 : Other personal service activities Part-time employees': '96_other_personal_service_activities_parttime_employees',
 '97 : Activities of households as employers of domestic personnel Employees': '97_households_with_domestic_personnel_employees',
 '97 : Activities of households as employers of domestic personnel Full-time employees': '97_households_with_domestic_personnel_fulltime_employees',
 '97 : Activities of households as employers of domestic personnel Part-time employees': '97_households_with_domestic_personnel_parttime_employees',
 '98 : Undifferentiated goods- and services-producing activities of private households for own use Employees': '98_activities_of_households_for_own_use_employees',
 '98 : Undifferentiated goods- and services-producing activities of private households for own use Full-time employees': '98_activities_of_households_for_own_use_fulltime_employees',
 '98 : Undifferentiated goods- and services-producing activities of private households for own use Part-time employees': '98_activities_of_households_for_own_use_parttime_employees',
 '99 : Activities of extraterritorial organisations and bodies Employees': '99_extraterr_orgs_employees',
 '99 : Activities of extraterritorial organisations and bodies Full-time employees': '99_extraterr_orgs_fulltime_employees',
 '99 : Activities of extraterritorial organisations and bodies Part-time employees': '99_extraterr_orgs_parttime_employees'
 }

disposable_income_reformat = {
    'GDHI per head (£)': 'gdhi_per_capita',
    'GDHI per head index (UK = 100)': 'gdhi_per_capita_index',
    'Gross Disposable Household Income - GDHI (£m)': 'gdhi_abs_million',
    'Growth in GDHI on year (%)': 'gdhi_abs_growth',
    'Growth in GDHI per head on year (%)': 'gdhi_per_capita_growth'
 }

jobs_density_reformat = {
    'Total jobs': 'total_jobs',
    'Jobs density': 'jobs_per_capita'
}

population_reformat = {
    'Aged 0 to 15': 'aged_0_to_15',
    'Aged 16 to 24': 'aged_16_to_24',
    'Aged 16 to 64': 'aged_16_to_64',
    'Aged 16+': 'aged_16_plus',
    'Aged 25 to 49': 'aged_25_to_49',
    'Aged 50 to 64': 'aged_50_to_64',
    'Aged 65+': 'aged_65_plus',
    'All Ages': 'all_ages'
 }